"use client";

import { useEffect,useState } from "react";
import { BookOpen,Loader2,Plus,Save,Sparkles } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Item={id:string;title:string;source:string;category:string;summary:string;application:string;tags:string[];createdAt?:string|null};
const field="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/20";

export default function LabLearningsPage(){
 const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[showForm,setShowForm]=useState(false);
 const[form,setForm]=useState({title:"",source:"Curso Luiz Main",category:"Ferramentas de IA",summary:"",application:"",tags:""});
 async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
 async function load(){setLoading(true);setError("");try{const response=await fetch("/api/internal/lab/learnings",{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Não foi possível carregar os aprendizados.");setItems(payload.items||[]);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar aprendizados.");}finally{setLoading(false);}}
 useEffect(()=>{const unsub=firebaseAuth.onAuthStateChanged(user=>{if(user)void load();});return unsub;},[]);
 async function save(){setSaving(true);setError("");try{const response=await fetch("/api/internal/lab/learnings",{method:"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({...form,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean)})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Não foi possível registrar o aprendizado.");setForm({title:"",source:"Curso Luiz Main",category:"Ferramentas de IA",summary:"",application:"",tags:""});setShowForm(false);await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar aprendizado.");}finally{setSaving(false);}}
 return <main className="min-h-screen bg-[#040c17] px-6 pb-20 pt-28 text-white"><div className="mx-auto max-w-6xl"><header className="border-b border-white/10 pb-7"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-violet-200"><BookOpen className="h-4 w-4"/>ALGENRI Lab · Aprendizados</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Caderno de aprendizados aplicáveis</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-white/50">Registre conceitos, ferramentas, testes e decisões de cursos e experimentos. O objetivo é transformar aprendizado em recurso reaproveitável na ALGENRI, no Studio e em futuros serviços.</p></header>
 <div className="mt-6 flex justify-end"><button onClick={()=>setShowForm(v=>!v)} className="inline-flex items-center gap-2 rounded-xl border border-violet-300/20 bg-violet-300/[.06] px-4 py-2.5 text-sm font-semibold text-violet-100"><Plus className="h-4 w-4"/>Novo aprendizado</button></div>
 {showForm&&<section className="mt-5 rounded-[26px] border border-violet-300/15 bg-violet-300/[.025] p-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-xs text-white/45">Título<input className={`${field} mt-2`} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Voz neural — ElevenLabs e MiniMax"/></label><label className="text-xs text-white/45">Fonte<input className={`${field} mt-2`} value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label className="text-xs text-white/45">Categoria<input className={`${field} mt-2`} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="text-xs text-white/45">Tags<input className={`${field} mt-2`} value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="voz, elevenlabs, minimax"/></label><label className="text-xs text-white/45 md:col-span-2">O que aprendi<textarea rows={5} className={`${field} mt-2 resize-y leading-6`} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label className="text-xs text-white/45 md:col-span-2">Como aplicar na ALGENRI<textarea rows={5} className={`${field} mt-2 resize-y leading-6`} value={form.application} onChange={e=>setForm({...form,application:e.target.value})}/></label></div><div className="mt-4 flex justify-end"><button onClick={save} disabled={saving||form.title.trim().length<2||form.summary.trim().length<3} className="inline-flex items-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/[.06] px-4 py-2.5 text-sm font-semibold text-emerald-100 disabled:opacity-35">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Salvar aprendizado</button></div></section>}
 {error&&<div className="mt-5 rounded-2xl border border-rose-300/15 bg-rose-300/[.04] p-4 text-sm text-rose-100">{error}</div>}
 <section className="mt-6 space-y-4">{loading?<div className="flex items-center gap-2 text-sm text-white/40"><Loader2 className="h-4 w-4 animate-spin"/>Carregando...</div>:items.length===0?<div className="rounded-[24px] border border-dashed border-white/10 p-6 text-sm text-white/35">Ainda não há registros. O curso do Luiz Main pode ser o primeiro conjunto de aprendizados desta área.</div>:items.map(item=><article key={item.id} className="rounded-[24px] border border-white/10 bg-white/[.02] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.12em] text-violet-200/70"><Sparkles className="h-3.5 w-3.5"/>{item.category}</div><h2 className="mt-2 text-lg font-semibold">{item.title}</h2><p className="mt-1 text-xs text-white/35">{item.source}</p></div><div className="flex flex-wrap gap-1.5">{item.tags.map(tag=><span key={tag} className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] text-white/35">{tag}</span>)}</div></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/8 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Aprendizado</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/60">{item.summary}</p></div><div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[.02] p-4"><p className="text-[10px] uppercase tracking-[.12em] text-cyan-100/45">Aplicação na ALGENRI</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/60">{item.application||"Ainda não definida."}</p></div></div></article>)}</section>
 </div></main>;
}
