"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Captions, CheckCircle2, Download, Film, Loader2, Music2, PackageCheck, Save, Smartphone, Square, Monitor } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Delivery = {
  variants: ("9:16"|"16:9"|"1:1"|"4:5")[];
  destinations: string[];
  subtitles: { enabled:boolean; format:"srt"|"vtt"|"both"; burnIn:boolean; style:"clean"|"social"|"minimal"; safeArea:number };
  soundtrack: { enabled:boolean; libraryItemId?:string; label?:string; volume:number; ducking:boolean; fadeInSeconds:number; fadeOutSeconds:number };
  includeScenes:boolean; includeAudio:boolean; includeCaptions:boolean; includeThumbnail:boolean;
};

type Payload = { delivery:Delivery; captions:{srt:string;vtt:string;cues:any[]}; packageManifest:{baseRenderReady:boolean;files:{kind:string;name:string;ready:boolean}[]} };
const box="rounded-[24px] border border-white/10 bg-white/[.025] p-5";
const input="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none";
const formats:[Delivery["variants"][number],string,any][]=[["9:16","Vertical",Smartphone],["16:9","Horizontal",Monitor],["1:1","Quadrado",Square],["4:5","Feed",Film]];

export default function StudioDeliveryPage({params}:{params:Promise<{projectId:string}>}){
  const [projectId,setProjectId]=useState(""); const [data,setData]=useState<Payload|null>(null); const [form,setForm]=useState<Delivery|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{params.then(({projectId})=>setProjectId(projectId))},[params]);
  async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
  async function load(){if(!projectId)return;setLoading(true);setMessage("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/delivery`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Falha ao carregar entrega.");setData(payload);setForm(payload.delivery);}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar entrega.");}finally{setLoading(false)}}
  useEffect(()=>{if(projectId){const unsub=firebaseAuth.onAuthStateChanged(user=>user&&void load());return unsub;}},[projectId]);
  async function save(){if(!form)return;setSaving(true);setMessage("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/delivery`,{method:"PUT",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Falha ao salvar.");setMessage("Configuração de entrega salva.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha ao salvar.");}finally{setSaving(false)}}
  function toggleVariant(value:Delivery["variants"][number]){if(!form)return;const has=form.variants.includes(value);const next=has?form.variants.filter(v=>v!==value):[...form.variants,value];if(next.length)setForm({...form,variants:next});}
  function downloadText(name:string,text:string,type:string){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
  return <main className="min-h-screen bg-[#040c17] px-5 pb-24 pt-24 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
    <a href={`/interno/lab/studio/projetos/${projectId}`} className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft className="h-4 w-4"/>Voltar ao projeto</a>
    <header className="mt-5 border-b border-white/10 pb-7"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-200"><PackageCheck className="h-4 w-4"/>ALGENRI Studio · Entrega</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Render, formatos e pacote de entrega</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-white/50">Organize versões por formato, legendas, trilha e arquivos de entrega sem regenerar cenas nem consumir créditos de IA.</p></header>
    {loading&&<div className="mt-6 flex items-center gap-2 text-sm text-white/45"><Loader2 className="h-4 w-4 animate-spin"/>Carregando...</div>}
    {form&&<>
      <section className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{formats.map(([value,label,Icon])=><button key={value} type="button" onClick={()=>toggleVariant(value)} className={`${box} text-left ${form.variants.includes(value)?"border-cyan-300/25 bg-cyan-300/[.05]":""}`}><Icon className="h-5 w-5 text-cyan-200"/><p className="mt-3 font-semibold">{label}</p><p className="mt-1 text-xs text-white/40">{value}</p></button>)}</section>
      <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className={box}><div className="flex items-center gap-2"><Captions className="h-5 w-5 text-violet-200"/><h2 className="font-semibold">Legendas</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="flex items-center gap-2 text-xs text-white/55"><input type="checkbox" checked={form.subtitles.enabled} onChange={e=>setForm({...form,subtitles:{...form.subtitles,enabled:e.target.checked}})}/>Ativar legendas</label><label className="flex items-center gap-2 text-xs text-white/55"><input type="checkbox" checked={form.subtitles.burnIn} onChange={e=>setForm({...form,subtitles:{...form.subtitles,burnIn:e.target.checked}})}/>Incorporar ao vídeo</label><label className="text-xs text-white/55">Formato<select className={input} value={form.subtitles.format} onChange={e=>setForm({...form,subtitles:{...form.subtitles,format:e.target.value as any}})}><option value="srt">SRT</option><option value="vtt">VTT</option><option value="both">SRT + VTT</option></select></label><label className="text-xs text-white/55">Estilo<select className={input} value={form.subtitles.style} onChange={e=>setForm({...form,subtitles:{...form.subtitles,style:e.target.value as any}})}><option value="clean">Clean</option><option value="social">Social</option><option value="minimal">Minimal</option></select></label><label className="text-xs text-white/55 md:col-span-2">Safe area (%)<input type="number" min="0" max="30" className={input} value={form.subtitles.safeArea} onChange={e=>setForm({...form,subtitles:{...form.subtitles,safeArea:Number(e.target.value)}})}/></label></div>{data?.captions?.cues?.length?<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>downloadText("legendas.srt",data.captions.srt,"application/x-subrip")} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/65">Baixar SRT</button><button onClick={()=>downloadText("legendas.vtt",data.captions.vtt,"text/vtt")} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/65">Baixar VTT</button></div>:<p className="mt-4 text-xs text-white/35">As legendas serão derivadas da locução aprovada do storyboard.</p>}</div>
      <div className={box}><div className="flex items-center gap-2"><Music2 className="h-5 w-5 text-emerald-200"/><h2 className="font-semibold">Trilha sonora</h2></div><label className="mt-4 flex items-center gap-2 text-xs text-white/55"><input type="checkbox" checked={form.soundtrack.enabled} onChange={e=>setForm({...form,soundtrack:{...form.soundtrack,enabled:e.target.checked}})}/>Usar trilha no render</label><label className="mt-4 block text-xs text-white/55">Referência / biblioteca<input className={input} value={form.soundtrack.label||""} onChange={e=>setForm({...form,soundtrack:{...form.soundtrack,label:e.target.value}})} placeholder="Ex.: Corporate cinematic 01"/></label><label className="mt-4 block text-xs text-white/55">Volume ({Math.round(form.soundtrack.volume*100)}%)<input type="range" min="0" max="1" step="0.01" className="mt-3 w-full" value={form.soundtrack.volume} onChange={e=>setForm({...form,soundtrack:{...form.soundtrack,volume:Number(e.target.value)}})}/></label><label className="mt-4 flex items-center gap-2 text-xs text-white/55"><input type="checkbox" checked={form.soundtrack.ducking} onChange={e=>setForm({...form,soundtrack:{...form.soundtrack,ducking:e.target.checked}})}/>Reduzir trilha automaticamente durante a narração</label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs text-white/55">Fade in<input type="number" min="0" max="10" step="0.1" className={input} value={form.soundtrack.fadeInSeconds} onChange={e=>setForm({...form,soundtrack:{...form.soundtrack,fadeInSeconds:Number(e.target.value)}})}/></label><label className="text-xs text-white/55">Fade out<input type="number" min="0" max="10" step="0.1" className={input} value={form.soundtrack.fadeOutSeconds} onChange={e=>setForm({...form,soundtrack:{...form.soundtrack,fadeOutSeconds:Number(e.target.value)}})}/></label></div></div></section>
      <section className={`mt-5 ${box}`}><h2 className="font-semibold">Pacote de entrega</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Cenas individuais","includeScenes"],["Áudio/narração","includeAudio"],["Legendas","includeCaptions"],["Thumbnail","includeThumbnail"]].map(([label,key])=><label key={key} className="flex items-center gap-2 rounded-xl border border-white/10 bg-black/15 px-3 py-3 text-xs text-white/55"><input type="checkbox" checked={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.checked} as Delivery)}/>{label}</label>)}</div>{data?.packageManifest&&<div className="mt-4 space-y-2">{data.packageManifest.files.map(file=><div key={file.name} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/15 px-3 py-2 text-xs"><span className="text-white/55">{file.name}</span><span className={file.ready?"text-emerald-200":"text-white/25"}>{file.ready?"pronto":"pendente"}</span></div>)}</div>}</section>
      <div className="mt-5 flex items-center justify-between gap-3"><p className="text-xs text-white/35">A criação de versões alternativas fica preparada aqui; nenhum vídeo adicional é gerado automaticamente.</p><button onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/[.08] px-4 py-3 text-sm font-semibold text-cyan-100 disabled:opacity-40">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Salvar entrega</button></div>
      {message&&<p className="mt-4 text-xs text-emerald-200">{message}</p>}
    </>}
  </div></main>;
}
