"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Mic2, Save, Sparkles } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Scene = { index:number; title:string; narration:string };
type Profile = { id:string; name:string; providerPreference:string; language:string; tone?:string; emotion?:string; pace?:string; pronunciationNotes?:string; directionNotes?:string; isDefault?:boolean };
type SceneDirection = { sceneIndex:number; emotion:string; pace:"inherit"|"slow"|"natural"|"dynamic"; emphasis:string; pronunciationNotes:string; directionNotes:string };
type Project = { id:string; name:string; storyboard?:Scene[]; voiceDirection?:{ profileId?:string|null; mode?:"single_track"|"per_scene"; globalDirection?:string; globalPronunciationNotes?:string; sceneDirections?:SceneDirection[]; profileSnapshot?:Profile|null } };

const box="rounded-[24px] border border-white/10 bg-white/[.025] p-5";
const input="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none placeholder:text-white/25 focus:border-cyan-300/25";

export default function ProjectVoiceDirectionPage({params}:{params:Promise<{projectId:string}>}){
  const [projectId,setProjectId]=useState(""); const [project,setProject]=useState<Project|null>(null); const [profiles,setProfiles]=useState<Profile[]>([]); const [profileId,setProfileId]=useState(""); const [mode,setMode]=useState<"single_track"|"per_scene">("per_scene"); const [globalDirection,setGlobalDirection]=useState(""); const [globalPronunciation,setGlobalPronunciation]=useState(""); const [sceneDirections,setSceneDirections]=useState<SceneDirection[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{params.then(({projectId})=>setProjectId(projectId));},[params]);
  async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sua sessão expirou.");return user.getIdToken();}
  useEffect(()=>{if(!projectId)return;const unsub=firebaseAuth.onAuthStateChanged(async()=>{setLoading(true);try{const auth=await token();const [pRes,vRes]=await Promise.all([fetch(`/api/internal/studio/projects/${projectId}`,{headers:{Authorization:`Bearer ${auth}`},cache:"no-store"}),fetch(`/api/internal/studio/voice-profiles`,{headers:{Authorization:`Bearer ${auth}`},cache:"no-store"})]);const p=await pRes.json();const v=await vRes.json();if(!pRes.ok||!p.project)throw new Error(p.error||"Falha ao carregar projeto.");setProject(p.project);setProfiles(v.profiles||[]);const vd=p.project.voiceDirection||{};setProfileId(vd.profileId||"");setMode(vd.mode||"per_scene");setGlobalDirection(vd.globalDirection||"");setGlobalPronunciation(vd.globalPronunciationNotes||"");const storyboard=(p.project.storyboard||[]) as Scene[];const current=(vd.sceneDirections||[]) as SceneDirection[];setSceneDirections(storyboard.map(scene=>current.find(x=>x.sceneIndex===scene.index)||{sceneIndex:scene.index,emotion:"",pace:"inherit",emphasis:"",pronunciationNotes:"",directionNotes:""}));}catch(error){setMessage(error instanceof Error?error.message:"Falha ao carregar.");}finally{setLoading(false);}});return unsub;},[projectId]);
  const selected=useMemo(()=>profiles.find(p=>p.id===profileId)||null,[profiles,profileId]);
  function changeScene(index:number,patch:Partial<SceneDirection>){setSceneDirections(items=>items.map(item=>item.sceneIndex===index?{...item,...patch}:item));}
  async function save(){setSaving(true);setMessage("");try{const auth=await token();const response=await fetch(`/api/internal/studio/projects/${projectId}/voice-direction`,{method:"PUT",headers:{Authorization:`Bearer ${auth}`,"Content-Type":"application/json"},body:JSON.stringify({profileId:profileId||null,mode,globalDirection,globalPronunciationNotes:globalPronunciation,sceneDirections})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Não foi possível salvar.");setMessage("Direção de voz salva. Nenhuma geração de áudio foi executada.");}catch(error){setMessage(error instanceof Error?error.message:"Falha ao salvar.");}finally{setSaving(false);}}
  if(loading)return <main className="min-h-screen bg-[#040c17] px-6 pt-28 text-white"><div className="mx-auto max-w-6xl text-sm text-white/45">Carregando direção de voz...</div></main>;
  return <main className="min-h-screen bg-[#040c17] px-5 pb-24 pt-24 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
    <a href={`/interno/lab/studio/projetos/${projectId}`} className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft className="h-4 w-4"/>Voltar ao projeto</a>
    <header className="mt-5 border-b border-white/10 pb-7"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-200"><Mic2 className="h-4 w-4"/>ALGENRI Studio · Direção de voz</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">{project?.name||"Projeto"}</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-white/50">Defina a voz do projeto e as exceções por cena. Esta área apenas prepara o pipeline; geração ElevenLabs/MiniMax permanece desligada até ação explícita futura.</p></header>
    <section className="mt-7 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className={box}><h2 className="font-semibold">Perfil principal</h2><label className="mt-4 block text-xs text-white/50">Perfil da Biblioteca<select className={input} value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">Sem perfil vinculado</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}{p.isDefault?" · padrão":""}</option>)}</select></label>{selected&&<div className="mt-4 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.03] p-4 text-xs leading-5 text-white/50"><p className="font-semibold text-cyan-100">{selected.name}</p><p className="mt-2">{selected.language} · {selected.providerPreference==="undecided"?"provedor a definir":selected.providerPreference}</p><p className="mt-1">{[selected.tone,selected.emotion,selected.pace].filter(Boolean).join(" · ")}</p></div>}<label className="mt-4 block text-xs text-white/50">Estratégia<select className={input} value={mode} onChange={e=>setMode(e.target.value as any)}><option value="per_scene">Locução por cena</option><option value="single_track">Faixa única</option></select></label><label className="mt-4 block text-xs text-white/50">Direção global<textarea rows={5} className={input} value={globalDirection} onChange={e=>setGlobalDirection(e.target.value)} placeholder="Energia, intenção, pausas, dicção e ritmo do projeto."/></label><label className="mt-4 block text-xs text-white/50">Pronúncias globais<textarea rows={4} className={input} value={globalPronunciation} onChange={e=>setGlobalPronunciation(e.target.value)} placeholder="Ex.: ALGENRI = AL - GEN - RI"/></label></div>
      <div className={box}><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-violet-200"/><h2 className="font-semibold">Direção por cena</h2></div><p className="mt-2 text-xs leading-5 text-white/40">Use apenas quando uma cena precisar sair do padrão do perfil principal.</p><div className="mt-4 space-y-4">{(project?.storyboard||[]).map(scene=>{const d=sceneDirections.find(x=>x.sceneIndex===scene.index)||{sceneIndex:scene.index,emotion:"",pace:"inherit" as const,emphasis:"",pronunciationNotes:"",directionNotes:""};return <article key={scene.index} className="rounded-2xl border border-white/10 bg-black/10 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-cyan-200/70">Cena {scene.index}</p><h3 className="mt-1 text-sm font-semibold">{scene.title}</h3><p className="mt-2 text-xs leading-5 text-white/35">{scene.narration||"Sem locução definida."}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs text-white/45">Emoção<input className={input} value={d.emotion} onChange={e=>changeScene(scene.index,{emotion:e.target.value})}/></label><label className="text-xs text-white/45">Ritmo<select className={input} value={d.pace} onChange={e=>changeScene(scene.index,{pace:e.target.value as SceneDirection["pace"]})}><option value="inherit">Herdar perfil</option><option value="slow">Calmo</option><option value="natural">Natural</option><option value="dynamic">Dinâmico</option></select></label><label className="text-xs text-white/45 md:col-span-2">Ênfases<input className={input} value={d.emphasis} onChange={e=>changeScene(scene.index,{emphasis:e.target.value})} placeholder="Palavras ou trechos que merecem destaque."/></label><label className="text-xs text-white/45">Pronúncia específica<textarea rows={3} className={input} value={d.pronunciationNotes} onChange={e=>changeScene(scene.index,{pronunciationNotes:e.target.value})}/></label><label className="text-xs text-white/45">Direção específica<textarea rows={3} className={input} value={d.directionNotes} onChange={e=>changeScene(scene.index,{directionNotes:e.target.value})}/></label></div></article>})}</div></div></section>
    <div className="mt-5 flex flex-wrap items-center gap-3"><button onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/[.07] px-4 py-3 text-sm font-semibold text-emerald-100 disabled:opacity-40"><Save className="h-4 w-4"/>{saving?"Salvando...":"Salvar direção de voz"}</button><a href="/interno/lab/studio/vozes" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/55"><Mic2 className="h-4 w-4"/>Biblioteca de Vozes</a>{message&&<span className="inline-flex items-center gap-2 text-xs text-emerald-200"><CheckCircle2 className="h-4 w-4"/>{message}</span>}</div>
  </div></main>;
}
