"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { Building2, FolderKanban, Plus, Save } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Client = { id:string; legalName:string; tradeName:string; taxId:string; segment:string; city:string; state:string; country:string; website:string; instagram:string; email:string; phone:string; whatsapp:string; primaryContact:{name:string;role:string;email:string;phone:string}; relationshipStatus:string; notes:string; updatedAt:string };
type Project = { id:string; clientId:string; clientName:string; name:string; projectType:string; status:string; responsibleName:string; startDate:string; expectedDeliveryDate:string; description:string; notes:string; updatedAt:string };

async function authFetch(user: User, input: RequestInfo | URL, init?: RequestInit) {
  const token = await user.getIdToken();
  return fetch(input, { ...init, headers: { ...(init?.headers ?? {}), Authorization: `Bearer ${token}` } });
}

const blankClient = { legalName:"", tradeName:"", taxId:"", segment:"", city:"", state:"", country:"Brasil", website:"", instagram:"", email:"", phone:"", whatsapp:"", primaryContact:{name:"",role:"",email:"",phone:""}, relationshipStatus:"lead", notes:"" };
const blankProject = { name:"", projectType:"", status:"diagnosis", responsibleName:"", startDate:"", expectedDeliveryDate:"", description:"", notes:"" };

const clientLabels: Record<string,string> = { lead:"Lead", negotiation:"Em negociação", active:"Cliente ativo", paused:"Pausado", inactive:"Inativo", archived:"Arquivado" };
const projectLabels: Record<string,string> = { diagnosis:"Diagnóstico", briefing:"Briefing", proposal:"Proposta", contract:"Contrato", onboarding:"Onboarding", development:"Em desenvolvimento", validation:"Homologação", publication:"Publicação", delivery:"Entrega", support:"Suporte", completed:"Concluído", paused:"Pausado", cancelled:"Cancelado" };

export default function ClientsProjectsAdmin() {
  const [user,setUser]=useState<User|null>(null); const [ready,setReady]=useState(false); const [clients,setClients]=useState<Client[]>([]); const [selected,setSelected]=useState<Client|null>(null); const [projects,setProjects]=useState<Project[]>([]); const [clientForm,setClientForm]=useState<any>(blankClient); const [projectForm,setProjectForm]=useState<any>(blankProject); const [creatingClient,setCreatingClient]=useState(false); const [creatingProject,setCreatingProject]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setUser(u);setReady(true)}),[]);

  async function loadClients(activeUser=user){ if(!activeUser)return; const r=await authFetch(activeUser,"/api/internal/clients"); const p=await r.json(); if(!r.ok) throw new Error("Não foi possível carregar os clientes."); setClients(p.clients??[]); }
  async function openClient(id:string){ if(!user)return; const r=await authFetch(user,`/api/internal/clients/${id}`); const p=await r.json(); if(!r.ok) throw new Error("Não foi possível abrir o cliente."); setSelected(p.client); setClientForm(p.client); setProjects(p.projects??[]); setCreatingClient(false); setMessage(""); }
  useEffect(()=>{ if(user) loadClients(user).catch(e=>setMessage(e.message)); },[user]);

  async function saveClient(){ if(!user)return; setMessage(""); const editing=!!selected && !creatingClient; const r=await authFetch(user, editing?`/api/internal/clients/${selected.id}`:"/api/internal/clients", { method: editing?"PATCH":"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(clientForm) }); const p=await r.json(); if(!r.ok){setMessage(p.error==="client_name_required"?"Informe o nome fantasia ou a razão social.":"Não foi possível salvar o cliente.");return;} await loadClients(user); await openClient(p.client.id); setMessage(editing?"Cliente atualizado.":"Cliente criado com sucesso."); }
  async function saveProject(){ if(!user||!selected)return; const r=await authFetch(user,"/api/internal/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...projectForm,clientId:selected.id})}); const p=await r.json(); if(!r.ok){setMessage(p.error==="project_name_required"?"Informe o nome do projeto.":"Não foi possível criar o projeto.");return;} setProjectForm(blankProject); setCreatingProject(false); await openClient(selected.id); setMessage("Projeto criado com sucesso."); }

  if(!ready) return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Carregando…</main>;
  if(!user) return <main className="min-h-screen bg-[#040c17] grid place-items-center px-6 text-center text-white">Faça login primeiro em <strong>/interno</strong>.</main>;

  const setField=(key:string,value:string)=>setClientForm((f:any)=>({...f,[key]:value}));
  const input="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40";
  return <main className="min-h-screen bg-[#040c17] text-white"><header className="border-b border-white/10 bg-[#06111f]/90 px-6 py-5"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold tracking-[.25em] text-cyan-300">ALGENRI CLIENT FLOW</p><div className="mt-1 flex items-center justify-between"><h1 className="text-2xl font-semibold">Clientes e Projetos</h1><button onClick={()=>{setCreatingClient(true);setSelected(null);setProjects([]);setClientForm(blankClient);setMessage("")}} className="flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950"><Plus size={16}/>Novo cliente</button></div></div></header>
  <div className="mx-auto grid max-w-7xl gap-6 px-6 py-8 lg:grid-cols-[320px_1fr]">
    <aside className="space-y-3">{clients.map(c=><button key={c.id} onClick={()=>openClient(c.id)} className={`w-full rounded-2xl border p-4 text-left ${selected?.id===c.id?"border-cyan-400/40 bg-cyan-400/10":"border-white/10 bg-white/[.025]"}`}><div className="flex items-start gap-3"><Building2 className="mt-1 h-4 w-4 text-cyan-300"/><div><p className="font-medium">{c.tradeName||c.legalName}</p><p className="mt-1 text-xs text-slate-400">{c.segment||"Segmento não informado"}</p><p className="mt-2 text-xs text-slate-500">{clientLabels[c.relationshipStatus]??c.relationshipStatus}</p></div></div></button>)}{!clients.length&&<p className="text-sm text-slate-400">Nenhum cliente cadastrado.</p>}</aside>
    <section className="rounded-3xl border border-white/10 bg-white/[.025] p-6 md:p-8">{(selected||creatingClient)?<><div className="flex flex-col justify-between gap-3 border-b border-white/10 pb-5 md:flex-row"><div><p className="text-xs text-cyan-300">{creatingClient?"NOVO CLIENTE":"VISÃO 360° DO CLIENTE"}</p><h2 className="mt-2 text-2xl font-semibold">{creatingClient?"Cadastrar cliente":selected?.tradeName||selected?.legalName}</h2></div><button onClick={saveClient} className="flex items-center gap-2 self-start rounded-xl border border-cyan-300/25 px-4 py-2.5 text-sm text-cyan-100"><Save size={16}/>Salvar cliente</button></div>
      <div className="mt-6 grid gap-3 md:grid-cols-2"><input className={input} placeholder="Nome fantasia" value={clientForm.tradeName||""} onChange={e=>setField("tradeName",e.target.value)}/><input className={input} placeholder="Razão social" value={clientForm.legalName||""} onChange={e=>setField("legalName",e.target.value)}/><input className={input} placeholder="CNPJ" value={clientForm.taxId||""} onChange={e=>setField("taxId",e.target.value)}/><input className={input} placeholder="Segmento" value={clientForm.segment||""} onChange={e=>setField("segment",e.target.value)}/><input className={input} placeholder="Cidade" value={clientForm.city||""} onChange={e=>setField("city",e.target.value)}/><input className={input} placeholder="UF" value={clientForm.state||""} onChange={e=>setField("state",e.target.value)}/><input className={input} placeholder="Site" value={clientForm.website||""} onChange={e=>setField("website",e.target.value)}/><input className={input} placeholder="Instagram" value={clientForm.instagram||""} onChange={e=>setField("instagram",e.target.value)}/><input className={input} placeholder="E-mail" value={clientForm.email||""} onChange={e=>setField("email",e.target.value)}/><input className={input} placeholder="WhatsApp" value={clientForm.whatsapp||""} onChange={e=>setField("whatsapp",e.target.value)}/><select className={input} value={clientForm.relationshipStatus||"lead"} onChange={e=>setField("relationshipStatus",e.target.value)}>{Object.entries(clientLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input className={input} placeholder="Contato principal" value={clientForm.primaryContact?.name||""} onChange={e=>setClientForm((f:any)=>({...f,primaryContact:{...f.primaryContact,name:e.target.value}}))}/></div><textarea className={`${input} mt-3 min-h-24 w-full`} placeholder="Observações" value={clientForm.notes||""} onChange={e=>setField("notes",e.target.value)}/>
      {selected&&<div className="mt-8 border-t border-white/10 pt-6"><div className="flex items-center justify-between"><div><p className="text-xs tracking-[.2em] text-violet-200">PROJETOS</p><h3 className="mt-1 text-xl font-semibold">Projetos do cliente</h3></div><button onClick={()=>setCreatingProject(v=>!v)} className="flex items-center gap-2 rounded-xl border border-violet-300/25 px-4 py-2.5 text-sm text-violet-100"><Plus size={16}/>Novo projeto</button></div>
      {creatingProject&&<div className="mt-4 grid gap-3 rounded-2xl border border-violet-300/15 bg-violet-300/[.03] p-4 md:grid-cols-2"><input className={input} placeholder="Nome do projeto" value={projectForm.name} onChange={e=>setProjectForm((f:any)=>({...f,name:e.target.value}))}/><input className={input} placeholder="Tipo do projeto" value={projectForm.projectType} onChange={e=>setProjectForm((f:any)=>({...f,projectType:e.target.value}))}/><select className={input} value={projectForm.status} onChange={e=>setProjectForm((f:any)=>({...f,status:e.target.value}))}>{Object.entries(projectLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input className={input} placeholder="Responsável ALGENRI" value={projectForm.responsibleName} onChange={e=>setProjectForm((f:any)=>({...f,responsibleName:e.target.value}))}/><textarea className={`${input} md:col-span-2 min-h-20`} placeholder="Descrição" value={projectForm.description} onChange={e=>setProjectForm((f:any)=>({...f,description:e.target.value}))}/><button onClick={saveProject} className="rounded-xl bg-violet-200 px-4 py-2.5 text-sm font-semibold text-slate-950 md:col-span-2">Criar projeto</button></div>}
      <div className="mt-4 grid gap-3 md:grid-cols-2">{projects.map(p=><a key={p.id} href={`/interno/projetos/${p.id}`} className="rounded-2xl border border-white/10 bg-black/10 p-4 transition hover:border-cyan-300/25"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{p.name}</p><p className="mt-1 text-sm text-slate-400">{p.projectType||"Tipo não informado"}</p></div><FolderKanban className="h-5 w-5 text-cyan-300"/></div><p className="mt-3 text-xs text-cyan-200">{projectLabels[p.status]??p.status}</p></a>)}{!projects.length&&!creatingProject&&<p className="text-sm text-slate-400">Nenhum projeto cadastrado.</p>}</div></div>}</>:<div className="grid min-h-[480px] place-items-center text-center text-slate-500"><p>Selecione um cliente ou cadastre o primeiro.</p></div>}{message&&<p className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 px-4 py-3 text-sm text-amber-100">{message}</p>}</section>
  </div></main>;
}
