"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { ArrowLeft, ChevronLeft, ChevronRight, Save } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Project = { id:string; clientId:string; clientName:string; name:string; projectType:string; status:string; responsibleName:string; startDate:string; expectedDeliveryDate:string; description:string; notes:string };
type Client = { id:string; tradeName:string; legalName:string };
const projectLabels: Record<string,string> = { diagnosis:"Diagnóstico", briefing:"Briefing", proposal:"Proposta", contract:"Contrato", onboarding:"Onboarding", development:"Em desenvolvimento", validation:"Homologação", publication:"Publicação", delivery:"Entrega", support:"Suporte", completed:"Concluído", paused:"Pausado", cancelled:"Cancelado" };
const cycleStages = ["diagnosis","briefing","proposal","contract","onboarding","development","validation","publication","delivery","support","completed"];

async function authFetch(user: User, input: RequestInfo | URL, init?: RequestInit) {
  const token = await user.getIdToken();
  return fetch(input, { ...init, headers: { ...(init?.headers ?? {}), Authorization: `Bearer ${token}` } });
}

export default function ProjectDetailAdmin({ id }: { id: string }) {
  const [user,setUser]=useState<User|null>(null); const [ready,setReady]=useState(false); const [project,setProject]=useState<Project|null>(null); const [client,setClient]=useState<Client|null>(null); const [message,setMessage]=useState(""); const [changingStage,setChangingStage]=useState(false);
  useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setUser(u);setReady(true)}),[]);
  async function load(activeUser=user){ if(!activeUser)return; const r=await authFetch(activeUser,`/api/internal/projects/${id}`); const p=await r.json(); if(!r.ok) throw new Error("Não foi possível abrir o projeto."); setProject(p.project); setClient(p.client); }
  useEffect(()=>{ if(user) load(user).catch(e=>setMessage(e.message)); },[user,id]);
  async function save(){ if(!user||!project)return; const r=await authFetch(user,`/api/internal/projects/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(project)}); const p=await r.json(); if(!r.ok){setMessage("Não foi possível salvar o projeto.");return;} setProject(p.project); setMessage("Projeto atualizado."); }
  async function changeStage(status:string){ if(!user||!project||changingStage||status===project.status)return; setChangingStage(true); setMessage(""); const next={...project,status}; const r=await authFetch(user,`/api/internal/projects/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)}); const p=await r.json(); if(!r.ok){setMessage("Não foi possível alterar a etapa do projeto.");setChangingStage(false);return;} setProject(p.project); setMessage(`Etapa alterada para ${projectLabels[status]}.`); setChangingStage(false); }
  if(!ready) return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Carregando…</main>;
  if(!user) return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Faça login em /interno.</main>;
  if(!project) return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">{message||"Carregando projeto…"}</main>;
  const input="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40";
  const cycleIndex=cycleStages.indexOf(project.status); const previousStage=cycleIndex>0?cycleStages[cycleIndex-1]:null; const nextStage=cycleIndex>=0&&cycleIndex<cycleStages.length-1?cycleStages[cycleIndex+1]:null;
  return <main className="min-h-screen bg-[#040c17] px-6 py-10 text-white"><div className="mx-auto max-w-5xl"><a href="/interno/clientes" className="inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={16}/>Clientes</a><div className="mt-6 flex flex-col justify-between gap-4 border-b border-white/10 pb-6 md:flex-row md:items-start"><div><p className="text-xs font-semibold tracking-[.22em] text-cyan-300">PROJETO</p><h1 className="mt-2 text-3xl font-semibold">{project.name}</h1><p className="mt-2 text-sm text-slate-400">{client?.tradeName||client?.legalName||project.clientName}</p></div><button onClick={save} className="flex items-center gap-2 self-start rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950"><Save size={16}/>Salvar</button></div>
  <div className="mt-6 grid gap-4 md:grid-cols-2"><input className={input} value={project.name} onChange={e=>setProject({...project,name:e.target.value})} placeholder="Nome do projeto"/><input className={input} value={project.projectType} onChange={e=>setProject({...project,projectType:e.target.value})} placeholder="Tipo do projeto"/><select className={input} value={project.status} onChange={e=>setProject({...project,status:e.target.value})}>{Object.entries(projectLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input className={input} value={project.responsibleName} onChange={e=>setProject({...project,responsibleName:e.target.value})} placeholder="Responsável ALGENRI"/><input className={input} type="date" value={project.startDate||""} onChange={e=>setProject({...project,startDate:e.target.value})}/><input className={input} type="date" value={project.expectedDeliveryDate||""} onChange={e=>setProject({...project,expectedDeliveryDate:e.target.value})}/><textarea className={`${input} min-h-28 md:col-span-2`} value={project.description||""} onChange={e=>setProject({...project,description:e.target.value})} placeholder="Descrição"/><textarea className={`${input} min-h-24 md:col-span-2`} value={project.notes||""} onChange={e=>setProject({...project,notes:e.target.value})} placeholder="Observações"/></div>
  <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs tracking-[.2em] text-violet-200">CICLO DO PROJETO</p><p className="mt-1 text-sm text-white/45">Clique em uma etapa ou use os botões para avançar e retroceder.</p></div><div className="flex gap-2"><button disabled={!previousStage||changingStage} onClick={()=>previousStage&&changeStage(previousStage)} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-xs text-white/70 disabled:cursor-not-allowed disabled:opacity-30"><ChevronLeft size={14}/>Anterior</button><button disabled={!nextStage||changingStage} onClick={()=>nextStage&&changeStage(nextStage)} className="inline-flex items-center gap-1 rounded-xl border border-cyan-300/25 bg-cyan-300/[.08] px-3 py-2 text-xs font-semibold text-cyan-100 disabled:cursor-not-allowed disabled:opacity-30">Avançar etapa<ChevronRight size={14}/></button></div></div><div className="mt-4 flex flex-wrap gap-2">{cycleStages.map(k=><button type="button" disabled={changingStage} onClick={()=>changeStage(k)} key={k} className={`rounded-full border px-3 py-1.5 text-xs transition disabled:cursor-wait ${project.status===k?"border-cyan-300/40 bg-cyan-300/10 text-cyan-100":"border-white/10 text-white/35 hover:border-white/25 hover:text-white/70"}`}>{projectLabels[k]}</button>)}</div>{["paused","cancelled"].includes(project.status)&&<p className="mt-4 text-sm text-amber-100/80">Projeto atualmente marcado como {projectLabels[project.status]}. Selecione uma etapa do ciclo para retomá-lo.</p>}</section>
  {message&&<p className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 px-4 py-3 text-sm text-amber-100">{message}</p>}</div></main>;
}
