"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { ArrowLeft, ChevronLeft, ChevronRight, Copy, ExternalLink, FilePlus2, Link2, Save } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Project = { id:string; clientId:string; clientName:string; name:string; projectType:string; status:string; responsibleName:string; startDate:string; expectedDeliveryDate:string; description:string; notes:string };
type Client = { id:string; tradeName:string; legalName:string };
type Briefing = { id:string; clientName:string; projectName:string; slug:string; status:string; progress:number; templateName:string; templateVersion:string; completedAt:string|null; linkedAt:string|null };
type Dossier = { id:string; title:string; status:string; version:string; sourceBriefingInstanceId:string; updatedAt:string };
type Template = { id:string; name:string; version:string; status:string };

const projectLabels: Record<string,string> = { diagnosis:"Diagnóstico", briefing:"Briefing", proposal:"Proposta", contract:"Contrato", onboarding:"Onboarding", development:"Em desenvolvimento", validation:"Homologação", publication:"Publicação", delivery:"Entrega", support:"Suporte", completed:"Concluído", paused:"Pausado", cancelled:"Cancelado" };
const briefingLabels: Record<string,string> = { not_started:"Não iniciado", in_progress:"Em andamento", completed:"Concluído", archived:"Arquivado" };
const dossierLabels: Record<string,string> = { draft:"Rascunho", in_analysis:"Em análise", review_ready:"Pronto para revisão", finalized:"Finalizado", archived:"Arquivado" };
const cycleStages = ["diagnosis","briefing","proposal","contract","onboarding","development","validation","publication","delivery","support","completed"];

async function authFetch(user: User, input: RequestInfo | URL, init?: RequestInit) {
  const token = await user.getIdToken();
  return fetch(input, { ...init, headers: { ...(init?.headers ?? {}), Authorization: `Bearer ${token}` } });
}
function defaultSlug(clientName:string, projectName:string){ return `${clientName}-${projectName}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,64); }

export default function ProjectDetailAdmin({ id }: { id: string }) {
  const [user,setUser]=useState<User|null>(null); const [ready,setReady]=useState(false); const [project,setProject]=useState<Project|null>(null); const [client,setClient]=useState<Client|null>(null);
  const [briefings,setBriefings]=useState<Briefing[]>([]); const [unlinked,setUnlinked]=useState<Briefing[]>([]); const [dossiers,setDossiers]=useState<Dossier[]>([]); const [templates,setTemplates]=useState<Template[]>([]);
  const [message,setMessage]=useState(""); const [changingStage,setChangingStage]=useState(false); const [selectedLegacy,setSelectedLegacy]=useState(""); const [templateId,setTemplateId]=useState(""); const [slug,setSlug]=useState(""); const [accessUrl,setAccessUrl]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setUser(u);setReady(true)}),[]);

  async function load(activeUser=user){
    if(!activeUser)return;
    const [projectRes,briefingRes,unlinkedRes,dossierRes,templateRes]=await Promise.all([
      authFetch(activeUser,`/api/internal/projects/${id}`),
      authFetch(activeUser,`/api/internal/briefing/instances?projectId=${encodeURIComponent(id)}`),
      authFetch(activeUser,"/api/internal/briefing/instances?unlinked=true"),
      authFetch(activeUser,`/api/internal/dossiers?projectId=${encodeURIComponent(id)}`),
      authFetch(activeUser,"/api/internal/briefing/templates"),
    ]);
    const p=await projectRes.json(); if(!projectRes.ok) throw new Error("Não foi possível abrir o projeto.");
    setProject(p.project); setClient(p.client);
    const [b,u,d,t]=await Promise.all([briefingRes.json(),unlinkedRes.json(),dossierRes.json(),templateRes.json()]);
    setBriefings(briefingRes.ok?b.instances:[]); setUnlinked(unlinkedRes.ok?u.instances:[]); setDossiers(dossierRes.ok?d.dossiers:[]); setTemplates(templateRes.ok?t.templates.filter((x:Template)=>x.status==="published"):[]);
    if(!slug) setSlug(defaultSlug(p.client?.tradeName||p.client?.legalName||p.project.clientName,p.project.name));
  }
  useEffect(()=>{ if(user) load(user).catch(e=>setMessage(e.message)); },[user,id]);

  async function save(){ if(!user||!project)return; const r=await authFetch(user,`/api/internal/projects/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(project)}); const p=await r.json(); if(!r.ok){setMessage("Não foi possível salvar o projeto.");return;} setProject(p.project); setMessage("Projeto atualizado."); }
  async function changeStage(status:string){ if(!user||!project||changingStage||status===project.status)return; setChangingStage(true); setMessage(""); const r=await authFetch(user,`/api/internal/projects/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...project,status})}); const p=await r.json(); if(!r.ok){setMessage("Não foi possível alterar a etapa do projeto.");setChangingStage(false);return;} setProject(p.project); setMessage(`Etapa alterada para ${projectLabels[status]}.`); setChangingStage(false); }
  async function linkExisting(){ if(!user||!project||!selectedLegacy)return; if(!confirm("Confirmar o vínculo deste briefing ao cliente e projeto atuais? O link público, token, respostas e progresso não serão alterados."))return; setBusy(true); const r=await authFetch(user,`/api/internal/briefing/instances/${selectedLegacy}/link-project`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId:project.clientId,projectId:project.id})}); const p=await r.json(); if(!r.ok){setMessage(p.error==="briefing_already_linked"?"Este briefing já está vinculado a outro projeto.":"Não foi possível vincular o briefing.");setBusy(false);return;} setSelectedLegacy(""); setMessage("Briefing vinculado sem alterar o acesso da cliente."); await load(user); setBusy(false); }
  async function createBriefing(){ if(!user||!project||!templateId||!slug)return; setBusy(true); setAccessUrl(""); const r=await authFetch(user,"/api/internal/briefing/instances",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({templateId,clientId:project.clientId,projectId:project.id,clientName:project.clientName,projectName:project.name,slug})}); const p=await r.json(); if(!r.ok){setMessage(p.error==="slug_in_use"?"Este endereço de briefing já está em uso. Altere o identificador.":"Não foi possível criar o briefing.");setBusy(false);return;} setAccessUrl(p.accessUrl); setMessage("Briefing criado e vinculado ao projeto. O link abaixo é exibido nesta sessão."); await load(user); setBusy(false); }
  async function createDossier(briefingId:string){ if(!user)return; setBusy(true); const r=await authFetch(user,"/api/internal/dossiers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({briefingInstanceId:briefingId})}); const p=await r.json(); if(!r.ok){setMessage(p.error==="briefing_not_completed"?"O briefing precisa estar concluído antes de gerar o dossiê.":"Não foi possível gerar o dossiê.");setBusy(false);return;} setMessage(p.created?"Dossiê criado com sucesso.":"O dossiê deste briefing já existia."); await load(user); setBusy(false); }

  if(!ready) return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Carregando…</main>;
  if(!user) return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Faça login em /interno.</main>;
  if(!project) return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">{message||"Carregando projeto…"}</main>;
  const input="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40";
  const cycleIndex=cycleStages.indexOf(project.status); const previousStage=cycleIndex>0?cycleStages[cycleIndex-1]:null; const nextStage=cycleIndex>=0&&cycleIndex<cycleStages.length-1?cycleStages[cycleIndex+1]:null;
  const dossierByBriefing=new Map(dossiers.map(d=>[d.sourceBriefingInstanceId,d]));

  return <main className="min-h-screen bg-[#040c17] px-6 py-10 text-white"><div className="mx-auto max-w-5xl">
    <a href="/interno/clientes" className="inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={16}/>Clientes</a>
    <div className="mt-6 flex flex-col justify-between gap-4 border-b border-white/10 pb-6 md:flex-row md:items-start"><div><p className="text-xs font-semibold tracking-[.22em] text-cyan-300">PROJETO</p><h1 className="mt-2 text-3xl font-semibold">{project.name}</h1><p className="mt-2 text-sm text-slate-400">{client?.tradeName||client?.legalName||project.clientName}</p></div><button onClick={save} className="flex items-center gap-2 self-start rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950"><Save size={16}/>Salvar</button></div>

    <div className="mt-6 grid gap-4 md:grid-cols-2"><input className={input} value={project.name} onChange={e=>setProject({...project,name:e.target.value})} placeholder="Nome do projeto"/><input className={input} value={project.projectType} onChange={e=>setProject({...project,projectType:e.target.value})} placeholder="Tipo do projeto"/><select className={input} value={project.status} onChange={e=>setProject({...project,status:e.target.value})}>{Object.entries(projectLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input className={input} value={project.responsibleName} onChange={e=>setProject({...project,responsibleName:e.target.value})} placeholder="Responsável ALGENRI"/><input className={input} type="date" value={project.startDate||""} onChange={e=>setProject({...project,startDate:e.target.value})}/><input className={input} type="date" value={project.expectedDeliveryDate||""} onChange={e=>setProject({...project,expectedDeliveryDate:e.target.value})}/><textarea className={`${input} min-h-28 md:col-span-2`} value={project.description||""} onChange={e=>setProject({...project,description:e.target.value})} placeholder="Descrição"/><textarea className={`${input} min-h-24 md:col-span-2`} value={project.notes||""} onChange={e=>setProject({...project,notes:e.target.value})} placeholder="Observações"/></div>

    <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs tracking-[.2em] text-violet-200">CICLO DO PROJETO</p><p className="mt-1 text-sm text-white/45">A etapa do projeto é uma decisão operacional e não depende automaticamente dos documentos abaixo.</p></div><div className="flex gap-2"><button disabled={!previousStage||changingStage} onClick={()=>previousStage&&changeStage(previousStage)} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-xs text-white/70 disabled:opacity-30"><ChevronLeft size={14}/>Anterior</button><button disabled={!nextStage||changingStage} onClick={()=>nextStage&&changeStage(nextStage)} className="inline-flex items-center gap-1 rounded-xl border border-cyan-300/25 bg-cyan-300/[.08] px-3 py-2 text-xs font-semibold text-cyan-100 disabled:opacity-30">Avançar etapa<ChevronRight size={14}/></button></div></div><div className="mt-4 flex flex-wrap gap-2">{cycleStages.map(k=><button type="button" disabled={changingStage} onClick={()=>changeStage(k)} key={k} className={`rounded-full border px-3 py-1.5 text-xs transition ${project.status===k?"border-cyan-300/40 bg-cyan-300/10 text-cyan-100":"border-white/10 text-white/35 hover:border-white/25 hover:text-white/70"}`}>{projectLabels[k]}</button>)}</div></section>

    <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><p className="text-xs tracking-[.2em] text-cyan-200">BRIEFINGS DO PROJETO</p><p className="mt-1 text-sm text-white/45">Briefings vinculados por ID oficial ao cliente e ao projeto.</p></div><a href="/interno/briefings/recebidos" className="text-xs text-cyan-200 hover:text-cyan-100">Área de briefings <ExternalLink className="ml-1 inline h-3 w-3"/></a></div>
      <div className="mt-4 space-y-3">{briefings.length===0?<p className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-white/40">Nenhum briefing vinculado a este projeto.</p>:briefings.map(b=>{const dossier=dossierByBriefing.get(b.id);return <div key={b.id} className="rounded-xl border border-white/10 bg-black/15 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{b.templateName} <span className="text-xs text-white/35">v{b.templateVersion}</span></p><p className="mt-1 text-xs text-white/45">{briefingLabels[b.status]||b.status} · {b.progress}% respondido</p></div><div className="flex flex-wrap gap-2"><a href={`/interno/briefings/recebidos/${encodeURIComponent(b.id)}`} className="inline-flex items-center gap-1 rounded-lg border border-cyan-300/25 px-3 py-2 text-xs font-semibold text-cyan-100">Abrir briefing <ExternalLink size={12}/></a>{b.status==="completed"&&!dossier&&<button disabled={busy} onClick={()=>createDossier(b.id)} className="rounded-lg bg-violet-300 px-3 py-2 text-xs font-semibold text-slate-950">Gerar Dossiê</button>}{dossier&&<a href="/interno/dossies" className="rounded-lg border border-violet-300/25 px-3 py-2 text-xs text-violet-100">Dossiê {dossierLabels[dossier.status]||dossier.status}</a>}</div></div></div>})}</div>

      <div className="mt-6 grid gap-4 border-t border-white/10 pt-5 md:grid-cols-2"><div className="rounded-xl border border-white/10 p-4"><p className="text-sm font-semibold">Vincular briefing existente</p><p className="mt-1 text-xs leading-5 text-white/40">Use para briefings criados antes do cadastro oficial de Clientes e Projetos.</p><select className={`${input} mt-3 w-full`} value={selectedLegacy} onChange={e=>setSelectedLegacy(e.target.value)}><option value="">Selecione…</option>{unlinked.map(b=><option key={b.id} value={b.id}>{b.clientName} — {b.templateName} v{b.templateVersion} ({briefingLabels[b.status]||b.status})</option>)}</select><button disabled={!selectedLegacy||busy} onClick={linkExisting} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-cyan-300/25 px-3 py-2 text-xs font-semibold text-cyan-100 disabled:opacity-40"><Link2 size={14}/>Confirmar vínculo</button></div>
      <div className="rounded-xl border border-white/10 p-4"><p className="text-sm font-semibold">Criar novo briefing</p><p className="mt-1 text-xs leading-5 text-white/40">Cliente e projeto serão vinculados automaticamente.</p><select className={`${input} mt-3 w-full`} value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Modelo publicado…</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} v{t.version}</option>)}</select><input className={`${input} mt-2 w-full`} value={slug} onChange={e=>setSlug(e.target.value)} placeholder="endereço-do-briefing"/><button disabled={!templateId||!slug||busy} onClick={createBriefing} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-3 py-2 text-xs font-semibold text-slate-950 disabled:opacity-40"><FilePlus2 size={14}/>Criar briefing</button></div></div>
      {accessUrl&&<div className="mt-4 rounded-xl border border-emerald-300/20 bg-emerald-300/[.05] p-4"><p className="text-xs font-semibold text-emerald-100">Novo link de acesso — copie agora</p><p className="mt-2 break-all text-xs text-white/60">{accessUrl}</p><div className="mt-3 flex gap-2"><button onClick={()=>navigator.clipboard.writeText(accessUrl)} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs"><Copy size={13}/>Copiar</button><a href={accessUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs"><ExternalLink size={13}/>Testar</a></div></div>}
    </section>

    <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><p className="text-xs tracking-[.2em] text-violet-200">DOSSIÊS</p><p className="mt-1 text-sm text-white/45">Gerados a partir de briefings concluídos e vinculados.</p></div><a href="/interno/dossies" className="text-xs text-violet-200 hover:text-violet-100">Abrir área <ExternalLink className="ml-1 inline h-3 w-3"/></a></div>{dossiers.length===0?<p className="mt-4 rounded-xl border border-dashed border-white/10 p-4 text-sm text-white/40">Nenhum dossiê criado para este projeto.</p>:<div className="mt-4 space-y-2">{dossiers.map(d=><div key={d.id} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/15 p-4"><div><p className="text-sm font-medium">{d.title}</p><p className="mt-1 text-xs text-white/40">Versão {d.version} · {dossierLabels[d.status]||d.status}</p></div></div>)}</div>}</section>

    {message&&<p className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 px-4 py-3 text-sm text-amber-100">{message}</p>}
  </div></main>;
}
