"use client";

import { useEffect, useMemo, useState } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { CheckCircle2, CircleDollarSign, Plus, ReceiptText, TriangleAlert } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Client = { id:string; tradeName:string; legalName:string };
type Project = { id:string; clientId:string; name:string };
type Charge = { id:string; clientId:string; clientName:string; projectId:string; projectName:string; description:string; amountCents:number; dueDate:string; status:"pending"|"paid"|"cancelled"; paidAt:string|null; paymentMethod:string; notes:string };

async function authFetch(user: User, input: RequestInfo | URL, init?: RequestInit) {
  const token = await user.getIdToken();
  return fetch(input, { ...init, headers: { ...(init?.headers ?? {}), Authorization: `Bearer ${token}` } });
}
const money=(cents:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(cents/100);
const blank={clientId:"",projectId:"",description:"",amount:"",dueDate:"",paymentMethod:"Pix",notes:""};

export default function FinanceAdmin() {
  const [user,setUser]=useState<User|null>(null); const [ready,setReady]=useState(false); const [clients,setClients]=useState<Client[]>([]); const [projects,setProjects]=useState<Project[]>([]); const [charges,setCharges]=useState<Charge[]>([]); const [form,setForm]=useState<any>(blank); const [creating,setCreating]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setUser(u);setReady(true)}),[]);
  async function load(active=user){ if(!active)return; const [cr,clr,pr]=await Promise.all([authFetch(active,"/api/internal/finance/charges"),authFetch(active,"/api/internal/clients"),authFetch(active,"/api/internal/projects")]); const [cp,clp,pp]=await Promise.all([cr.json(),clr.json(),pr.json()]); if(!cr.ok||!clr.ok||!pr.ok) throw new Error("Não foi possível carregar o financeiro."); setCharges(cp.charges??[]); setClients(clp.clients??[]); setProjects(pp.projects??[]); }
  useEffect(()=>{if(user)load(user).catch(e=>setMessage(e.message));},[user]);
  async function create(){ if(!user)return; setMessage(""); const r=await authFetch(user,"/api/internal/finance/charges",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const p=await r.json(); if(!r.ok){setMessage(p.error==="amount_required"?"Informe um valor válido.":p.error==="due_date_required"?"Informe o vencimento.":p.error==="description_required"?"Informe a descrição da cobrança.":"Não foi possível registrar a cobrança.");return;} setForm(blank);setCreating(false);await load(user);setMessage("Cobrança registrada com sucesso."); }
  async function mark(id:string,status:"paid"|"pending"|"cancelled",paymentMethod?:string){ if(!user)return; const r=await authFetch(user,`/api/internal/finance/charges/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,paymentMethod})}); if(!r.ok){setMessage("Não foi possível atualizar a cobrança.");return;} await load(user);setMessage(status==="paid"?"Recebimento confirmado.":"Cobrança atualizada."); }
  if(!ready)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Carregando…</main>;
  if(!user)return null;

  const today=new Date().toISOString().slice(0,10); const pending=charges.filter(c=>c.status==="pending"); const paid=charges.filter(c=>c.status==="paid"); const overdue=pending.filter(c=>c.dueDate<today); const totalPending=pending.reduce((s,c)=>s+c.amountCents,0); const totalPaid=paid.reduce((s,c)=>s+c.amountCents,0); const filteredProjects=projects.filter(p=>!form.clientId||p.clientId===form.clientId);
  const cards=[{label:"A receber",value:money(totalPending),icon:CircleDollarSign},{label:"Recebido",value:money(totalPaid),icon:CheckCircle2},{label:"Em aberto",value:String(pending.length),icon:ReceiptText},{label:"Vencidas",value:String(overdue.length),icon:TriangleAlert}];
  const input="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40";

  return <main className="min-h-screen bg-[#040c17] text-white"><header className="border-b border-white/10 bg-[#06111f]/90 px-6 py-5"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold tracking-[.25em] text-cyan-300">ALGENRI FINANCEIRO</p><div className="mt-1 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Controle financeiro</h1><p className="mt-1 text-sm text-white/45">Cobranças, vencimentos e recebimentos registrados manualmente.</p></div><button onClick={()=>setCreating(v=>!v)} className="flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950"><Plus size={16}/>Nova cobrança</button></div></div></header>
  <div className="mx-auto max-w-7xl px-6 py-8"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><p className="text-sm text-white/50">{label}</p><Icon className="h-4 w-4 text-cyan-300"/></div><p className="mt-3 text-2xl font-semibold">{value}</p></div>)}</div>
  {creating&&<section className="mt-6 rounded-3xl border border-cyan-300/15 bg-cyan-300/[.025] p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select className={input} value={form.clientId} onChange={e=>setForm((f:any)=>({...f,clientId:e.target.value,projectId:""}))}><option value="">Selecione o cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.tradeName||c.legalName}</option>)}</select><select className={input} value={form.projectId} onChange={e=>setForm((f:any)=>({...f,projectId:e.target.value}))}><option value="">Projeto (opcional)</option>{filteredProjects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className={input} placeholder="Descrição da cobrança" value={form.description} onChange={e=>setForm((f:any)=>({...f,description:e.target.value}))}/><input className={input} placeholder="Valor (ex.: 1.250,00)" value={form.amount} onChange={e=>setForm((f:any)=>({...f,amount:e.target.value}))}/><input className={input} type="date" value={form.dueDate} onChange={e=>setForm((f:any)=>({...f,dueDate:e.target.value}))}/><select className={input} value={form.paymentMethod} onChange={e=>setForm((f:any)=>({...f,paymentMethod:e.target.value}))}><option>Pix</option><option>Transferência</option><option>Boleto</option><option>Cartão</option><option>Outro</option></select><input className={`${input} xl:col-span-2`} placeholder="Observações" value={form.notes} onChange={e=>setForm((f:any)=>({...f,notes:e.target.value}))}/></div><div className="mt-4 flex justify-end"><button onClick={create} className="rounded-xl bg-cyan-300 px-5 py-2.5 text-sm font-semibold text-slate-950">Registrar cobrança</button></div></section>}
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><section id="cobrancas" className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><h2 className="text-lg font-semibold">Cobranças em aberto</h2><div className="mt-4 space-y-3">{pending.map(c=><div key={c.id} className={`rounded-2xl border p-4 ${c.dueDate<today?"border-rose-300/20 bg-rose-300/[.035]":"border-white/10 bg-black/10"}`}><div className="flex items-start justify-between gap-4"><div><p className="font-medium">{c.clientName}</p><p className="mt-1 text-sm text-white/55">{c.description}</p><p className="mt-2 text-xs text-white/35">{c.projectName||"Sem projeto vinculado"} · venc. {c.dueDate.split("-").reverse().join("/")}</p></div><p className="font-semibold text-cyan-100">{money(c.amountCents)}</p></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>mark(c.id,"paid",c.paymentMethod||"Pix")} className="rounded-lg border border-emerald-300/20 px-3 py-1.5 text-xs text-emerald-100">Marcar como recebido</button><button onClick={()=>mark(c.id,"cancelled")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-white/40">Cancelar</button></div></div>)}{!pending.length&&<p className="text-sm text-white/35">Nenhuma cobrança em aberto.</p>}</div></section>
  <section id="recebimentos" className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><h2 className="text-lg font-semibold">Recebimentos</h2><div className="mt-4 space-y-3">{paid.map(c=><div key={c.id} className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-medium">{c.clientName}</p><p className="mt-1 text-sm text-white/55">{c.description}</p><p className="mt-2 text-xs text-white/35">{c.paymentMethod||"Forma não informada"}{c.paidAt?` · ${new Date(c.paidAt).toLocaleDateString("pt-BR")}`:""}</p></div><p className="font-semibold text-emerald-100">{money(c.amountCents)}</p></div></div>)}{!paid.length&&<p className="text-sm text-white/35">Nenhum recebimento registrado.</p>}</div></section></div>{message&&<p className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 px-4 py-3 text-sm text-amber-100">{message}</p>}</div></main>;
}
