"use client";
import { useEffect,useState } from "react";
import { onAuthStateChanged,type User } from "firebase/auth";
import { ExternalLink,FilePlus2 } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";
type Proposal={id:string;proposalNumber:string;version:string;status:string;total:number;recurringMonthly:number}; type Dossier={id:string;title:string;status:string;version:string};
const labels:Record<string,string>={draft:"Rascunho",in_review:"Em revisão",ready_to_send:"Pronta para envio",sent:"Enviada",negotiation:"Em negociação",approved:"Aprovada",rejected:"Rejeitada",expired:"Expirada",archived:"Arquivada"};
async function authFetch(user:User,url:string,init?:RequestInit){const token=await user.getIdToken();return fetch(url,{...init,headers:{...(init?.headers??{}),Authorization:`Bearer ${token}`}})} const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function ProjectProposalsPanel({projectId}:{projectId:string}){const [user,setUser]=useState<User|null>(null),[proposals,setProposals]=useState<Proposal[]>([]),[dossiers,setDossiers]=useState<Dossier[]>([]),[dossierId,setDossierId]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>onAuthStateChanged(firebaseAuth,setUser),[]);async function load(u=user){if(!u)return;const [a,b]=await Promise.all([authFetch(u,`/api/internal/proposals?projectId=${encodeURIComponent(projectId)}`),authFetch(u,`/api/internal/dossiers?projectId=${encodeURIComponent(projectId)}`)]);const [pa,pb]=await Promise.all([a.json(),b.json()]);setProposals(a.ok?pa.proposals:[]);setDossiers(b.ok?pb.dossiers:[])}useEffect(()=>{if(user)load(user)},[user,projectId]);async function create(){if(!user||busy)return;setBusy(true);const r=await authFetch(user,"/api/internal/proposals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,dossierId:dossierId||undefined})});const p=await r.json();setBusy(false);if(!r.ok){setMessage("Não foi possível criar a proposta.");return;}window.location.href=`/interno/propostas/${p.proposal.id}`}
return <section className="bg-[#040c17] px-6 pb-12 text-white"><div className="mx-auto max-w-5xl rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><p className="text-xs tracking-[.2em] text-cyan-200">PROPOSTAS COMERCIAIS</p><p className="mt-1 text-sm text-white/45">Propostas vinculadas a este projeto.</p></div><a href="/interno/propostas" className="text-xs text-cyan-200">Abrir área <ExternalLink className="ml-1 inline h-3 w-3"/></a></div><div className="mt-4 space-y-2">{proposals.length===0?<p className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-white/40">Nenhuma proposta criada para este projeto.</p>:proposals.map(p=><a key={p.id} href={`/interno/propostas/${p.id}`} className="flex flex-col justify-between gap-2 rounded-xl border border-white/10 bg-black/15 p-4 sm:flex-row sm:items-center"><div><p className="text-sm font-medium">{p.proposalNumber} · v{p.version}</p><p className="mt-1 text-xs text-white/40">{labels[p.status]||p.status}</p></div><p className="text-sm text-cyan-100">{money(p.total)}{p.recurringMonthly>0?` + ${money(p.recurringMonthly)}/mês`:""}</p></a>)}</div><div className="mt-5 grid gap-3 border-t border-white/10 pt-4 md:grid-cols-[1fr_auto]"><select value={dossierId} onChange={e=>setDossierId(e.target.value)} className="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm"><option value="">Criar proposta manual</option>{dossiers.map(d=><option key={d.id} value={d.id}>A partir de: {d.title} · v{d.version}</option>)}</select><button disabled={busy} onClick={create} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-40"><FilePlus2 size={15}/>{busy?"Criando…":"Nova proposta"}</button></div>{message&&<p className="mt-3 text-sm text-amber-100">{message}</p>}</div></section>}
