"use client";
import { useEffect,useState } from "react";
import { onAuthStateChanged,type User } from "firebase/auth";
import { ArrowLeft, Plus, Save, Sparkles } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Section={id:string;key:string;title:string;content:string;order:number;source:string;editable:boolean};
type Item={id:string;description:string;quantity:number;unitValue:number;totalValue:number;billingType:"one_time"|"recurring";recurrence:"monthly"|"annual"|"custom"|null;order:number};
type Proposal={id:string;proposalNumber:string;version:string;clientName:string;projectName:string;status:string;title:string;summary:string;sections:Section[];investmentItems:Item[];subtotal:number;discountType:"none"|"fixed"|"percentage";discountValue:number;total:number;recurringMonthly:number;recurringAnnual:number;paymentTerms:string;validityDate:string;commercialConditions:string;observations:string};
const labels:Record<string,string>={draft:"Rascunho",in_review:"Em revisão",ready_to_send:"Pronta para envio",sent:"Enviada",negotiation:"Em negociação",approved:"Aprovada",rejected:"Rejeitada",expired:"Expirada",archived:"Arquivada"};
async function authFetch(user:User,url:string,init?:RequestInit){const token=await user.getIdToken();return fetch(url,{...init,headers:{...(init?.headers??{}),Authorization:`Bearer ${token}`}})}
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function ProposalDetailAdmin({id}:{id:string}){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[proposal,setProposal]=useState<Proposal|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setUser(u);setReady(true)}),[]);
 async function load(u=user){if(!u)return;const r=await authFetch(u,`/api/internal/proposals/${id}`);const p=await r.json();if(!r.ok)throw new Error("Não foi possível abrir a proposta.");setProposal(p.proposal)}
 useEffect(()=>{if(user)load(user).catch(e=>setMessage(e.message))},[user,id]);
 async function save(){if(!user||!proposal||busy)return;setBusy(true);const r=await authFetch(user,`/api/internal/proposals/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(proposal)});const p=await r.json();setBusy(false);if(!r.ok){setMessage(p.error==="proposal_locked"?"Esta versão está protegida. Crie uma nova versão para alterar o conteúdo.":"Não foi possível salvar.");return;}setProposal(p.proposal);setMessage("Proposta salva.")}
 async function setStatus(status:string){if(!user||!proposal)return;const r=await authFetch(user,`/api/internal/proposals/${id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const p=await r.json();if(!r.ok){setMessage("Não foi possível alterar o status.");return;}setProposal(p.proposal);setMessage(`Status alterado para ${labels[status]||status}.`)}
 async function newVersion(){if(!user||!proposal)return;if(!confirm("Criar uma nova versão desta proposta preservando a versão atual?"))return;const r=await authFetch(user,`/api/internal/proposals/${id}/new-version`,{method:"POST"});const p=await r.json();if(!r.ok){setMessage("Não foi possível criar a nova versão.");return;}window.location.href=`/interno/propostas/${p.proposal.id}`}
 function addItem(){if(!proposal)return;setProposal({...proposal,investmentItems:[...proposal.investmentItems,{id:`item-${Date.now()}`,description:"",quantity:1,unitValue:0,totalValue:0,billingType:"one_time",recurrence:null,order:proposal.investmentItems.length}]})}
 const locked=proposal?!["draft","in_review"].includes(proposal.status):false; const input="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40";
 if(!ready)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Carregando…</main>; if(!user)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Faça login em /interno.</main>; if(!proposal)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">{message||"Carregando proposta…"}</main>;
 return <main className="min-h-screen bg-[#040c17] px-6 py-10 text-white"><div className="mx-auto max-w-5xl"><a href="/interno/propostas" className="inline-flex items-center gap-2 text-sm text-white/50"><ArrowLeft size={15}/>Propostas</a><div className="mt-6 flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-semibold tracking-[.2em] text-cyan-300">{proposal.proposalNumber} · v{proposal.version}</p><h1 className="mt-2 text-3xl font-semibold">{proposal.title}</h1><p className="mt-2 text-sm text-white/45">{proposal.clientName} — {proposal.projectName}</p></div><div className="flex flex-wrap gap-2">{locked?<button onClick={newVersion} className="rounded-xl bg-violet-300 px-4 py-2.5 text-sm font-semibold text-slate-950">Criar nova versão</button>:<button disabled={busy} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950"><Save size={15}/>Salvar</button>}</div></div>
 <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap gap-2">{Object.entries(labels).map(([k,v])=><button key={k} onClick={()=>setStatus(k)} className={`rounded-full border px-3 py-1.5 text-xs ${proposal.status===k?"border-cyan-300/40 bg-cyan-300/10 text-cyan-100":"border-white/10 text-white/45"}`}>{v}</button>)}</div>{locked&&<p className="mt-3 text-sm text-amber-100/75">Esta versão está protegida contra alterações comerciais.</p>}</section>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><input disabled={locked} className={input} value={proposal.title} onChange={e=>setProposal({...proposal,title:e.target.value})}/><input disabled={locked} type="date" className={input} value={proposal.validityDate||""} onChange={e=>setProposal({...proposal,validityDate:e.target.value})}/><textarea disabled={locked} className={`${input} min-h-24 md:col-span-2`} value={proposal.summary||""} onChange={e=>setProposal({...proposal,summary:e.target.value})} placeholder="Resumo executivo da proposta"/></div>
 <div className="mt-8 space-y-4">{proposal.sections.map((s,i)=><section key={s.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><input disabled={locked} className={`${input} w-full font-semibold`} value={s.title} onChange={e=>{const sections=[...proposal.sections];sections[i]={...s,title:e.target.value};setProposal({...proposal,sections})}}/><textarea disabled={locked} className={`${input} mt-3 min-h-36 w-full`} value={s.content||""} onChange={e=>{const sections=[...proposal.sections];sections[i]={...s,content:e.target.value};setProposal({...proposal,sections})}} placeholder="Conteúdo da seção"/></section>)}</div>
 <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><p className="text-xs tracking-[.2em] text-cyan-200">INVESTIMENTO</p><p className="mt-1 text-sm text-white/45">Valores únicos e recorrentes são apresentados separadamente.</p></div>{!locked&&<button onClick={addItem} className="inline-flex items-center gap-2 rounded-xl border border-cyan-300/25 px-3 py-2 text-xs text-cyan-100"><Plus size={14}/>Adicionar item</button>}</div><div className="mt-4 space-y-3">{proposal.investmentItems.map((it,i)=><div key={it.id} className="grid gap-2 rounded-xl border border-white/10 p-3 md:grid-cols-[2fr_.6fr_1fr_1fr_auto]"><input disabled={locked} className={input} value={it.description} onChange={e=>{const arr=[...proposal.investmentItems];arr[i]={...it,description:e.target.value};setProposal({...proposal,investmentItems:arr})}} placeholder="Descrição"/><input disabled={locked} className={input} type="number" min="0" step="1" value={it.quantity} onChange={e=>{const arr=[...proposal.investmentItems];arr[i]={...it,quantity:Number(e.target.value)};setProposal({...proposal,investmentItems:arr})}}/><input disabled={locked} className={input} type="number" min="0" step="0.01" value={it.unitValue} onChange={e=>{const arr=[...proposal.investmentItems];arr[i]={...it,unitValue:Number(e.target.value)};setProposal({...proposal,investmentItems:arr})}}/><select disabled={locked} className={input} value={it.billingType} onChange={e=>{const bt=e.target.value as "one_time"|"recurring";const arr=[...proposal.investmentItems];arr[i]={...it,billingType:bt,recurrence:bt==="recurring"?"monthly":null};setProposal({...proposal,investmentItems:arr})}}><option value="one_time">Único</option><option value="recurring">Recorrente</option></select>{!locked&&<button onClick={()=>setProposal({...proposal,investmentItems:proposal.investmentItems.filter((_,x)=>x!==i)})} className="rounded-lg border border-rose-300/20 px-3 text-xs text-rose-100">Excluir</button>}</div>)}</div>
 <div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/40">Investimento inicial</p><p className="mt-1 text-lg font-semibold">{money(proposal.total)}</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/40">Recorrência mensal</p><p className="mt-1 text-lg font-semibold">{money(proposal.recurringMonthly)}/mês</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/40">Recorrência anual</p><p className="mt-1 text-lg font-semibold">{money(proposal.recurringAnnual)}/ano</p></div></div>
 <div className="mt-4 grid gap-3 md:grid-cols-2"><select disabled={locked} className={input} value={proposal.discountType} onChange={e=>setProposal({...proposal,discountType:e.target.value as any})}><option value="none">Sem desconto</option><option value="fixed">Desconto fixo</option><option value="percentage">Desconto percentual</option></select><input disabled={locked} className={input} type="number" min="0" step="0.01" value={proposal.discountValue} onChange={e=>setProposal({...proposal,discountValue:Number(e.target.value)})} placeholder="Valor do desconto"/></div></section>
 <section className="mt-8 rounded-2xl border border-white/10 bg-white/[.025] p-5"><textarea disabled={locked} className={`${input} min-h-24 w-full`} value={proposal.paymentTerms||""} onChange={e=>setProposal({...proposal,paymentTerms:e.target.value})} placeholder="Condições de pagamento"/><textarea disabled={locked} className={`${input} mt-3 min-h-24 w-full`} value={proposal.commercialConditions||""} onChange={e=>setProposal({...proposal,commercialConditions:e.target.value})} placeholder="Condições comerciais"/><textarea disabled={locked} className={`${input} mt-3 min-h-20 w-full`} value={proposal.observations||""} onChange={e=>setProposal({...proposal,observations:e.target.value})} placeholder="Observações internas"/></section>
 {message&&<p className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-3 text-sm text-amber-100">{message}</p>}</div></main>
}
