"use client";
import { useEffect,useMemo,useState } from "react";
import { onAuthStateChanged,type User } from "firebase/auth";
import { FilePlus2, RefreshCcw } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Proposal={id:string;proposalNumber:string;version:string;clientName:string;projectName:string;status:string;total:number;recurringMonthly:number;validityDate:string;updatedAt:string};
type Project={id:string;name:string;clientName:string};
const labels:Record<string,string>={draft:"Rascunho",in_review:"Em revisão",ready_to_send:"Pronta para envio",sent:"Enviada",negotiation:"Em negociação",approved:"Aprovada",rejected:"Rejeitada",expired:"Expirada",archived:"Arquivada"};
async function authFetch(user:User,url:string,init?:RequestInit){const token=await user.getIdToken();return fetch(url,{...init,headers:{...(init?.headers??{}),Authorization:`Bearer ${token}`}})}
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
export default function ProposalsAdmin(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[proposals,setProposals]=useState<Proposal[]>([]),[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[title,setTitle]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("");
 useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setUser(u);setReady(true)}),[]);
 async function load(u=user){if(!u)return;const [a,b]=await Promise.all([authFetch(u,"/api/internal/proposals"),authFetch(u,"/api/internal/projects")]);const [pa,pb]=await Promise.all([a.json(),b.json()]);if(!a.ok||!b.ok)throw new Error("Não foi possível carregar propostas.");setProposals(pa.proposals??[]);setProjects(pb.projects??[])}
 useEffect(()=>{if(user)load(user).catch(e=>setMessage(e.message))},[user]);
 async function create(){if(!user||!projectId||busy)return;setBusy(true);setMessage("");const r=await authFetch(user,"/api/internal/proposals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,title,validityDays:15})});const p=await r.json();setBusy(false);if(!r.ok){setMessage("Não foi possível criar a proposta.");return;}window.location.href=`/interno/propostas/${p.proposal.id}`}
 const visible=useMemo(()=>proposals.filter(p=>`${p.proposalNumber} ${p.clientName} ${p.projectName}`.toLowerCase().includes(filter.toLowerCase())),[proposals,filter]);
 if(!ready)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Carregando…</main>; if(!user)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Faça login em /interno.</main>;
 const input="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm text-white outline-none";
 return <main className="min-h-screen bg-[#040c17] px-6 py-10 text-white"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold tracking-[.22em] text-cyan-300">ALGENRI CLIENT FLOW</p><h1 className="mt-2 text-3xl font-semibold">Propostas Comerciais</h1><p className="mt-2 text-sm text-white/45">Crie, versione e acompanhe propostas vinculadas aos projetos.</p></div><button onClick={()=>load().catch(()=>setMessage("Falha ao atualizar."))} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-sm"><RefreshCcw size={15}/>Atualizar</button></div>
 <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-sm font-semibold">+ Nova proposta</p><div className="mt-3 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select className={input} value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Selecione o projeto…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.clientName} — {p.name}</option>)}</select><input className={input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título opcional"/><button disabled={!projectId||busy} onClick={create} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-40"><FilePlus2 size={15}/>{busy?"Criando…":"Criar"}</button></div></section>
 <div className="mt-6"><input className={`${input} w-full md:w-96`} value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar proposta, cliente ou projeto"/></div>
 <div className="mt-4 space-y-3">{visible.map(p=><a key={p.id} href={`/interno/propostas/${p.id}`} className="block rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:border-cyan-300/25"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{p.proposalNumber} · v{p.version}</p><p className="mt-1 text-sm text-white/50">{p.clientName} — {p.projectName}</p></div><div className="text-left md:text-right"><p className="text-sm text-cyan-100">{money(p.total)}{p.recurringMonthly>0?` + ${money(p.recurringMonthly)}/mês`:""}</p><p className="mt-1 text-xs text-white/40">{labels[p.status]||p.status} · validade {p.validityDate||"—"}</p></div></div></a>)}{visible.length===0&&<p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-white/40">Nenhuma proposta encontrada.</p>}</div>{message&&<p className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-3 text-sm text-amber-100">{message}</p>}</div></main>;
}
