import { z } from "zod";
import { internalAuthResponse, requireAlgenriInternalUser } from "@/lib/briefing/internal-auth";
import { dryRunRunwayVideoRouter, getRunwayTask, generateRunwayVideoRouter, extractRunwayRoutingCost } from "@/lib/studio/runway";
import { createKieKling26TextToVideo, getKieCreditBalance, getKieTaskDetails, KIE_STUDIO_VIDEO_MODEL } from "@/lib/studio/kie";
import { getStudioProject, upsertStudioSceneGenerationJob, type StudioSceneGenerationJob } from "@/lib/studio/project-store";
import { archiveStudioOutput } from "@/lib/studio/output-storage";

const startSchema = z.object({ action:z.literal("start_scene"), sceneIndex:z.number().int().min(1), confirmSpend:z.literal(true), confirmUnknownCost:z.boolean().optional(), providerOverride:z.enum(["runway","kie-ai"]).optional() });
const refreshSchema = z.object({ action:z.literal("refresh_scene"), sceneIndex:z.number().int().min(1) });
const requestSchema = z.discriminatedUnion("action", [startSchema, refreshSchema]);

function normalizeRunwayStatus(value: unknown): StudioSceneGenerationJob["status"] { const status=String(value??"").toUpperCase(); if(["SUCCEEDED","SUCCESS","COMPLETED","DONE"].includes(status))return"succeeded"; if(["FAILED","CANCELLED","CANCELED"].includes(status))return"failed"; if(["RUNNING","PROCESSING","IN_PROGRESS","INPROGRESS"].includes(status))return"running"; return"queued"; }
function normalizeKieStatus(value: unknown): StudioSceneGenerationJob["status"] { const status=String(value??"").toLowerCase(); if(status==="success")return"succeeded"; if(status==="fail")return"failed"; if(status==="generating")return"running"; return"queued"; }
function firstOutputUrl(output: unknown) { if(!Array.isArray(output))return null; for(const item of output){ if(typeof item==="string"&&/^https?:\/\//.test(item))return item; if(item&&typeof item==="object"){const value=(item as any).url??(item as any).uri;if(typeof value==="string"&&/^https?:\/\//.test(value))return value;}} return null; }
function ratio(value: unknown): "16:9"|"9:16"|"1:1" { return value==="1:1"?"1:1":value==="9:16"||value==="4:5"?"9:16":"16:9"; }
function buildBrandSafeVisualPrompt(scene:any,project:any){const visualDirection=String(scene?.visualDirection??"").trim();const objective=String(scene?.objective??"").trim();const visualStyle=String(project?.briefing?.visualStyle??"").trim();const base=[visualDirection,objective?`Creative objective: ${objective}`:"",visualStyle?`Visual style: ${visualStyle}`:""].filter(Boolean).join("\n");return `${base}\n\nCRITICAL GENERATION RULES:\n- Generate ONLY the cinematic visual plate/background for this scene.\n- Do NOT render any logo, brand mark, company name, slogan, word, letter, number, caption, UI label, watermark or readable typography.\n- Do NOT invent or approximate a corporate logo or symbol.\n- Leave clean negative space when branding or copy will be added later.\n- Exact ALGENRI branding, logos and text are added after generation in the controlled composition layer.\n- Preserve the requested camera movement, lighting, environment, action and premium visual language without textual elements.`;}
async function archiveIfNeeded(input:{projectId:string;sceneIndex:number;job:StudioSceneGenerationJob;outputUrl:string|null;status:StudioSceneGenerationJob["status"]}){if(input.status!=="succeeded"||!input.outputUrl||input.job.storagePath)return{} as Partial<StudioSceneGenerationJob>;try{const archived=await archiveStudioOutput({projectId:input.projectId,sceneIndex:input.sceneIndex,provider:input.job.provider,taskId:input.job.taskId,outputUrl:input.outputUrl});return{storagePath:archived.storagePath,storageStatus:"archived" as const,storageError:null,contentType:archived.contentType,sizeBytes:archived.sizeBytes,archivedAt:archived.archivedAt};}catch(archiveError){console.error("studio_output_archive_failed",archiveError);return{storageStatus:"failed" as const,storageError:archiveError instanceof Error?archiveError.message:"studio_output_archive_failed"};}}

export async function POST(request:Request,context:{params:Promise<{projectId:string}>}){
 try{
  const user=await requireAlgenriInternalUser(request); const {projectId}=await context.params; const parsed=requestSchema.safeParse(await request.json()); if(!parsed.success)return Response.json({ok:false,error:"invalid_request",issues:parsed.error.issues},{status:400});
  const project=await getStudioProject(projectId); if(!project)return Response.json({ok:false,error:"not_found"},{status:404}); if(project.ownerUid&&project.ownerUid!==user.uid)return Response.json({ok:false,error:"forbidden"},{status:403});
  const scene=(project.storyboard??[]).find((item:any)=>item.index===parsed.data.sceneIndex); if(!scene)return Response.json({ok:false,error:"scene_not_found"},{status:404}); if(scene.status!=="approved")return Response.json({ok:false,error:"scene_not_approved"},{status:409});
  const route=(project.routing?.routes??[]).find((item:any)=>item.sceneIndex===scene.index); if(!route)return Response.json({ok:false,error:"scene_not_routed"},{status:409});
  const existing=(project.generation?.sceneJobs??[]).find((item:any)=>item.sceneIndex===scene.index) as StudioSceneGenerationJob|undefined;
  if(parsed.data.action==="start_scene"){
   if(existing&&["queued","running"].includes(existing.status))return Response.json({ok:false,error:"scene_generation_in_progress",job:existing},{status:409});
   const providerId=parsed.data.providerOverride??route.selectedProviderId; if(!["runway","kie-ai"].includes(providerId))return Response.json({ok:false,error:"provider_not_executable"},{status:409});
   const providerPrompt=buildBrandSafeVisualPrompt(scene,project); const budgetLimit=Number(project.briefing?.budgetLimit??0);
   if(providerId==="kie-ai"){
    const knownCost=typeof route.estimatedCredits==="number"&&Number.isFinite(route.estimatedCredits)&&route.estimatedCredits>0&&route.selectedProviderId==="kie-ai";
    if(!knownCost&&parsed.data.confirmUnknownCost!==true)return Response.json({ok:false,error:"unknown_cost_confirmation_required",provider:providerId,model:KIE_STUDIO_VIDEO_MODEL},{status:409});
    const balance=await getKieCreditBalance(); if(balance===null||balance<=0)return Response.json({ok:false,error:"kie_insufficient_credits",message:"Saldo Kie.ai insuficiente para iniciar uma nova geração.",balance,estimatedCredits:knownCost?route.estimatedCredits:null},{status:409}); if(knownCost&&balance<route.estimatedCredits)return Response.json({ok:false,error:"kie_insufficient_credits",message:`Saldo Kie.ai insuficiente. Disponível: ${balance} créditos; estimado: ${route.estimatedCredits}.`,balance,estimatedCredits:route.estimatedCredits},{status:409});
    const task=await createKieKling26TextToVideo({prompt:providerPrompt,aspectRatio:ratio(project.briefing?.aspectRatio),durationSeconds:scene.durationSeconds,sound:false}); const job:StudioSceneGenerationJob={sceneIndex:scene.index,provider:"kie-ai",model:KIE_STUDIO_VIDEO_MODEL,taskId:task.taskId,status:"queued",estimatedCredits:knownCost?route.estimatedCredits:null,actualCredits:null,outputUrl:null,storagePath:null,storageStatus:null,failure:null,startedAt:new Date().toISOString(),completedAt:null}; await upsertStudioSceneGenerationJob(projectId,job); return Response.json({ok:true,job,balanceBefore:balance,unknownCostAccepted:!knownCost,replacesTaskId:existing?.taskId??null,providerOverride:parsed.data.providerOverride??null},{status:201});
   }
   const dryRun=await dryRunRunwayVideoRouter({promptText:providerPrompt,aspectRatio:ratio(project.briefing?.aspectRatio),duration:Math.min(30,Math.max(1,scene.durationSeconds))}); const dryRouting:any=dryRun.routing??null; const preflightCredits=extractRunwayRoutingCost(dryRouting); if(typeof preflightCredits!=="number")return Response.json({ok:false,error:"runway_cost_estimate_unavailable",message:"O Runway não retornou estimativa de créditos para esta cena. A geração foi bloqueada antes de qualquer consumo."},{status:409}); if(budgetLimit>0&&preflightCredits>budgetLimit)return Response.json({ok:false,error:"budget_limit_exceeded",budgetLimit,estimatedCredits:preflightCredits},{status:409});
   const task=await generateRunwayVideoRouter({promptText:providerPrompt,aspectRatio:ratio(project.briefing?.aspectRatio),duration:Math.min(30,Math.max(1,scene.durationSeconds))}); const taskId=task.id??task.taskId??null; if(!taskId)return Response.json({ok:false,error:"runway_missing_task_id",providerPayload:task},{status:502}); const routing:any=task.routing??dryRouting; const estimatedCredits=extractRunwayRoutingCost(routing)??preflightCredits; const job:StudioSceneGenerationJob={sceneIndex:scene.index,provider:"runway",model:routing?.model??routing?.selectedModel??routing?.modelId??null,taskId,status:"queued",estimatedCredits,actualCredits:null,outputUrl:null,storagePath:null,storageStatus:null,failure:null,startedAt:new Date().toISOString(),completedAt:null}; await upsertStudioSceneGenerationJob(projectId,job); return Response.json({ok:true,job,replacesTaskId:existing?.taskId??null,providerOverride:parsed.data.providerOverride??null},{status:201});
  }
  if(!existing?.taskId)return Response.json({ok:false,error:"scene_generation_not_started"},{status:409});
  if(existing.provider==="kie-ai"){const task=await getKieTaskDetails(existing.taskId);const status=normalizeKieStatus(task.state);const outputUrl=task.resultUrls[0]??existing.outputUrl;const completed=status==="succeeded"||status==="failed";const storageFields=await archiveIfNeeded({projectId,sceneIndex:scene.index,job:existing,outputUrl,status});const job:StudioSceneGenerationJob={...existing,...storageFields,model:task.model??existing.model,status,outputUrl,failure:task.failMsg??task.failCode??null,actualCredits:task.creditsConsumed??existing.actualCredits??null,completedAt:completed?(existing.completedAt??new Date().toISOString()):null};await upsertStudioSceneGenerationJob(projectId,job);return Response.json({ok:true,job,progress:task.progress});}
  const task=await getRunwayTask(existing.taskId);const status=normalizeRunwayStatus(task.status);const outputUrl=firstOutputUrl(task.output)??existing.outputUrl;const completed=status==="succeeded"||status==="failed";const actualCredits=typeof(task as any).costCredits==="number"?(task as any).costCredits:typeof(task as any).creditsUsed==="number"?(task as any).creditsUsed:existing.actualCredits;const storageFields=await archiveIfNeeded({projectId,sceneIndex:scene.index,job:existing,outputUrl,status});const job:StudioSceneGenerationJob={...existing,...storageFields,status,outputUrl,failure:task.failure??null,actualCredits:actualCredits??null,completedAt:completed?(existing.completedAt??new Date().toISOString()):null};await upsertStudioSceneGenerationJob(projectId,job);return Response.json({ok:true,job});
 }catch(error){const auth=internalAuthResponse(error);if(auth)return auth;const providerError=error as Error&{status?:number;payload?:any};console.error("studio_scene_production_failed",error);const providerMessage=typeof providerError.payload?.msg==="string"?providerError.payload.msg:null;const friendlyMessage=providerError.message==="kie_insufficient_credits"?"A Kie.ai recusou a geração por saldo insuficiente. Recarregue os créditos ou escolha outro motor antes de tentar novamente.":providerError.message==="kie_unauthorized"?"A Kie.ai recusou a autenticação. Verifique a API key configurada na Vercel.":providerError.message==="kie_validation_failed"?`A Kie.ai recusou os parâmetros desta geração${providerMessage?`: ${providerMessage}`:"."}`:providerError.message==="kie_rate_limited"?"A Kie.ai limitou temporariamente novas requisições. Aguarde um pouco antes de tentar novamente.":providerMessage||providerError.message||"Falha ao iniciar a geração.";return Response.json({ok:false,error:friendlyMessage,code:providerError.message||"studio_scene_production_failed",providerStatus:providerError.status??null},{status:providerError.status===402?402:502});}
}
