"use client";

import { useEffect,useMemo,useState } from "react";
import { CheckCircle2,ImageUp,Layers3,Loader2,Save,ShieldCheck,Sparkles,Trash2,WandSparkles } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Scene={index:number;title:string};
type Job={sceneIndex:number;version?:number;status:string;outputUrl?:string|null;provider?:string;model?:string|null};
type Brand={mode:"algenri"|"asset"|"text"|"none";name:string;logoStoragePath?:string|null;logoContentType?:string|null};
type Preset="editorial"|"commercial"|"minimal";
type Overlay={sceneIndex:number;enabled:boolean;eyebrow:string;headline:string;body:string;cta:string;align:"left"|"center"|"right";position:"top"|"center"|"bottom";showBrand:boolean;offsetX:number;offsetY:number;widthPercent:number;scalePercent:number;panelOpacity:number};
export type StudioCompositionClient={state:"draft"|"approved";brand:Brand;preset:Preset;sceneOverlays:Overlay[];transition:"cut"|"fade";approvedAt:string|null;updatedAt:string};

function slider(label:string,value:number,min:number,max:number,onChange:(value:number)=>void,suffix="%"){return <label className="grid gap-1.5 text-[11px] text-white/45"><span className="flex justify-between"><span>{label}</span><strong className="text-white/65">{value}{suffix}</strong></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} className="accent-cyan-300"/></label>}

export default function StudioCompositionPanel({projectId,storyboard,generation,onCompositionChange}:{projectId:string;storyboard:Scene[];generation?:any;onCompositionChange?:(composition:StudioCompositionClient)=>void}){
  const[composition,setComposition]=useState<StudioCompositionClient|null>(null);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[brandPreview,setBrandPreview]=useState("");
  const activeJobs=(generation?.sceneJobs??[]) as Job[];const ready=storyboard.length>0&&storyboard.every(scene=>activeJobs.some(job=>job.sceneIndex===scene.index&&job.status==="succeeded"));const jobByScene=useMemo(()=>new Map(activeJobs.map(job=>[job.sceneIndex,job])),[activeJobs]);
  async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
  async function loadBrandPreview(brand?:Brand){if(brand?.mode!=="asset"||!brand.logoStoragePath){setBrandPreview("");return;}try{const response=await fetch(`/api/internal/studio/projects/${projectId}/brand`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});if(!response.ok)return;const url=URL.createObjectURL(await response.blob());setBrandPreview(current=>{if(current.startsWith("blob:"))URL.revokeObjectURL(current);return url;});}catch{}}
  async function load(){if(!ready)return;setBusy("load");setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/composition`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.composition)throw new Error(payload.error||"Não foi possível carregar a composição.");setComposition(payload.composition);onCompositionChange?.(payload.composition);void loadBrandPreview(payload.composition.brand);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar composição.");}finally{setBusy("");}}
  useEffect(()=>{if(ready)void load();return()=>{if(brandPreview.startsWith("blob:"))URL.revokeObjectURL(brandPreview);};},[ready,projectId]);
  function update(sceneIndex:number,patch:Partial<Overlay>){setComposition(current=>current?{...current,state:"draft",approvedAt:null,sceneOverlays:current.sceneOverlays.map(item=>item.sceneIndex===sceneIndex?{...item,...patch}:item)}:current);}
  function updateBrand(patch:Partial<Brand>){setComposition(current=>current?{...current,state:"draft",approvedAt:null,brand:{...current.brand,...patch}}:current);}
  function resetFineTune(sceneIndex:number){update(sceneIndex,{offsetX:0,offsetY:0,widthPercent:84,scalePercent:100,panelOpacity:58});}
  function applyPreset(preset:Preset){setComposition(current=>{if(!current)return current;const last=current.sceneOverlays.length-1;return{...current,state:"draft",approvedAt:null,preset,transition:preset==="minimal"?"cut":"fade",sceneOverlays:current.sceneOverlays.map((item,index)=>({...item,enabled:true,align:preset==="minimal"?"center":"left",position:preset==="minimal"?"center":index===last?"bottom":"center",body:preset==="minimal"?"":item.body,showBrand:preset==="minimal"?index===0&&current.brand.mode!=="none":current.brand.mode!=="none",offsetX:0,offsetY:0,widthPercent:preset==="minimal"?64:preset==="commercial"?88:84,scalePercent:preset==="minimal"?88:preset==="commercial"?106:100,panelOpacity:preset==="minimal"?34:preset==="commercial"?64:58}))};});}
  async function uploadLogo(file:File){setBusy("brand-upload");setError("");try{const form=new FormData();form.append("file",file);const response=await fetch(`/api/internal/studio/projects/${projectId}/brand`,{method:"POST",headers:{Authorization:`Bearer ${await token()}`},body:form});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.brand)throw new Error(payload.error||"Não foi possível enviar a logomarca.");setComposition(current=>current?{...current,state:"draft",approvedAt:null,brand:payload.brand}:current);await loadBrandPreview(payload.brand);}catch(e){setError(e instanceof Error?e.message:"Falha no upload da logomarca.");}finally{setBusy("");}}
  async function removeLogo(){setBusy("brand-delete");setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/brand`,{method:"DELETE",headers:{Authorization:`Bearer ${await token()}`}});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.brand)throw new Error(payload.error||"Não foi possível remover a logomarca.");setComposition(current=>current?{...current,state:"draft",approvedAt:null,brand:payload.brand}:current);if(brandPreview.startsWith("blob:"))URL.revokeObjectURL(brandPreview);setBrandPreview("");}catch(e){setError(e instanceof Error?e.message:"Falha ao remover logomarca.");}finally{setBusy("");}}
  async function save(approve=false){if(!composition)return;setBusy(approve?"approve":"save");setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/composition`,{method:"PATCH",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({brand:composition.brand,preset:composition.preset,sceneOverlays:composition.sceneOverlays,transition:composition.transition,approve})});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.composition)throw new Error(payload.error||"Não foi possível salvar a composição.");setComposition(payload.composition);onCompositionChange?.(payload.composition);}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar composição.");}finally{setBusy("");}}

  if(!ready)return <section className="mt-8 rounded-[28px] border border-white/10 bg-white/[.02] p-5 sm:p-6"><div className="flex gap-3"><Layers3 className="mt-0.5 h-5 w-5 text-white/40"/><div><h2 className="text-lg font-semibold">Composição controlada</h2><p className="mt-2 text-sm leading-6 text-white/40">Disponível quando todas as cenas tiverem uma versão ativa concluída.</p></div></div></section>;
  if(busy==="load"&&!composition)return <section className="mt-8 rounded-[28px] border border-cyan-300/15 bg-cyan-300/[.02] p-5 text-sm text-white/50"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Carregando composição...</section>;
  if(!composition)return null;
  const logoSrc=composition.brand.mode==="algenri"?"/algenri-logo.webp":composition.brand.mode==="asset"?brandPreview:"";

  return <section className="mt-8 rounded-[28px] border border-cyan-300/15 bg-cyan-300/[.025] p-5 sm:p-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-cyan-100"/><div><h2 className="text-lg font-semibold">Composição controlada</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/45">Além dos presets, cada cena agora aceita ajuste fino de largura, escala, posição horizontal/vertical e transparência para evitar cobrir pessoas ou elementos importantes.</p></div></div><span className={`self-start rounded-full px-3 py-1.5 text-xs ${composition.state==="approved"?"bg-emerald-300/10 text-emerald-100":"bg-amber-300/10 text-amber-100"}`}>{composition.state==="approved"?"Composição aprovada":"Rascunho"}</span></div>
    {error&&<div className="mt-4 rounded-2xl border border-rose-300/15 bg-rose-300/[.03] p-4 text-sm text-rose-100">{error}</div>}

    <div className="mt-5 rounded-2xl border border-white/10 bg-black/15 p-4"><div className="grid gap-3 md:grid-cols-[180px_1fr_auto] md:items-end"><label className="grid gap-2 text-xs text-white/45"><span>Marca do projeto</span><select value={composition.brand.mode} onChange={e=>updateBrand({mode:e.target.value as Brand["mode"]})} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white"><option value="algenri">Logo ALGENRI</option><option value="asset">Logo do projeto/cliente</option><option value="text">Marca textual</option><option value="none">Sem marca</option></select></label><label className="grid gap-2 text-xs text-white/45"><span>Nome da marca</span><input value={composition.brand.name} onChange={e=>updateBrand({name:e.target.value})} disabled={composition.brand.mode==="none"} placeholder="Nome da empresa ou marca" className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white outline-none disabled:opacity-35"/></label><label className="grid gap-2 text-xs text-white/45"><span>Transição</span><select value={composition.transition} onChange={e=>setComposition({...composition,state:"draft",approvedAt:null,transition:e.target.value as "cut"|"fade"})} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm text-white"><option value="fade">Fade suave</option><option value="cut">Corte direto</option></select></label></div><div className="mt-4 flex flex-wrap items-center gap-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-cyan-300/15 bg-cyan-300/[.05] px-3 py-2 text-xs font-semibold text-cyan-100"><ImageUp className="h-3.5 w-3.5"/> Enviar logomarca<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadLogo(file);e.currentTarget.value="";}}/></label>{composition.brand.mode==="asset"&&<button onClick={removeLogo} disabled={!!busy} className="inline-flex items-center gap-2 rounded-xl border border-rose-300/15 px-3 py-2 text-xs text-rose-100"><Trash2 className="h-3.5 w-3.5"/> Remover logo</button>}<span className="text-[11px] text-white/30">PNG, JPG ou WebP · até 5 MB</span></div></div>

    <div className="mt-4 rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] text-violet-100"><WandSparkles className="h-4 w-4"/> Presets reutilizáveis</div><div className="mt-3 flex flex-wrap gap-2">{([['editorial','Editorial'],['commercial','Comercial / CTA'],['minimal','Minimalista']] as [Preset,string][]).map(([value,label])=><button key={value} onClick={()=>applyPreset(value)} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${composition.preset===value?"border-violet-300/35 bg-violet-300/[.10] text-violet-50":"border-white/10 text-white/50"}`}>{label}</button>)}</div></div>

    <div className="mt-6 space-y-5">{composition.sceneOverlays.map(overlay=>{const scene=storyboard.find(item=>item.index===overlay.sceneIndex);const job=jobByScene.get(overlay.sceneIndex);const opacity=(overlay.panelOpacity??58)/100;const transform=`translate(${overlay.offsetX??0}%, ${overlay.offsetY??0}%) scale(${(overlay.scalePercent??100)/100})`;return <article key={overlay.sceneIndex} className="rounded-[24px] border border-white/10 bg-black/15 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.12em] text-cyan-200/60">Cena {overlay.sceneIndex}</p><h3 className="mt-1 font-semibold">{scene?.title||`Cena ${overlay.sceneIndex}`}</h3></div><label className="flex items-center gap-2 text-xs text-white/50"><input type="checkbox" checked={overlay.enabled} onChange={e=>update(overlay.sceneIndex,{enabled:e.target.checked})}/> Exibir camadas</label></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
      <div className="relative aspect-video overflow-hidden rounded-2xl border border-white/10 bg-[#07111f]">{job?.outputUrl?<video src={job.outputUrl} muted playsInline controls className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-white/30">Prévia da cena indisponível</div>}{overlay.enabled&&<div className={`pointer-events-none absolute inset-0 flex p-[6%] ${overlay.position==="top"?"items-start":overlay.position==="bottom"?"items-end":"items-center"} ${overlay.align==="center"?"justify-center text-center":overlay.align==="right"?"justify-end text-right":"justify-start text-left"}`}><div style={{width:`${overlay.widthPercent??84}%`,maxWidth:`${overlay.widthPercent??84}%`,transform,transformOrigin:overlay.align==="right"?"right center":overlay.align==="center"?"center center":"left center",backgroundColor:`rgba(6,21,34,${composition.preset==="minimal"?Math.min(opacity,.45):opacity})`}} className="relative overflow-hidden rounded-2xl border border-cyan-200/10 p-4 shadow-2xl backdrop-blur-[3px]"><div className={`absolute inset-y-0 left-0 bg-cyan-400/80 ${composition.preset==="minimal"?"w-0.5":"w-1"}`}/>{overlay.showBrand&&logoSrc&&<img src={logoSrc} alt={composition.brand.name||"Marca"} className="mb-4 ml-1 h-12 w-auto max-w-[62%] object-contain object-left"/>}{overlay.showBrand&&composition.brand.mode==="text"&&composition.brand.name&&<div className="mb-3 ml-1 text-[clamp(11px,1.2vw,16px)] font-semibold uppercase tracking-[.14em] text-cyan-100/90">{composition.brand.name}</div>}{overlay.eyebrow&&overlay.eyebrow.trim().toLowerCase()!==composition.brand.name.trim().toLowerCase()&&<div className="ml-1 text-[clamp(9px,1vw,13px)] uppercase tracking-[.14em] text-cyan-100/75">{overlay.eyebrow}</div>}{overlay.headline&&<div className="ml-1 mt-2 max-w-full break-words text-[clamp(16px,2.4vw,34px)] font-semibold leading-[1.08] text-white">{overlay.headline}</div>}{overlay.body&&<div className="ml-1 mt-2 max-w-full break-words text-[clamp(10px,1.2vw,15px)] leading-relaxed text-white/78">{overlay.body}</div>}{overlay.cta&&<div className="ml-1 mt-3 inline-flex max-w-full rounded-full border border-cyan-200/25 bg-cyan-500/20 px-3 py-1.5 text-[clamp(9px,1vw,13px)] font-semibold text-cyan-50">{overlay.cta}</div>}</div></div>}</div>
      <div className="grid gap-3"><input value={overlay.eyebrow} onChange={e=>update(overlay.sceneIndex,{eyebrow:e.target.value})} placeholder="Chamada curta" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><input value={overlay.headline} onChange={e=>update(overlay.sceneIndex,{headline:e.target.value})} placeholder="Título exato" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><textarea value={overlay.body} onChange={e=>update(overlay.sceneIndex,{body:e.target.value})} rows={3} placeholder="Texto complementar" className="resize-y rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><input value={overlay.cta} onChange={e=>update(overlay.sceneIndex,{cta:e.target.value})} placeholder="CTA" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><div className="grid grid-cols-2 gap-3"><select value={overlay.position} onChange={e=>update(overlay.sceneIndex,{position:e.target.value as Overlay["position"]})} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm"><option value="top">Topo</option><option value="center">Centro</option><option value="bottom">Rodapé</option></select><select value={overlay.align} onChange={e=>update(overlay.sceneIndex,{align:e.target.value as Overlay["align"]})} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm"><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></div><div className="grid gap-3 rounded-2xl border border-white/10 bg-white/[.02] p-3"><div className="flex items-center justify-between"><span className="text-[11px] font-semibold uppercase tracking-[.12em] text-cyan-100/70">Ajuste fino</span><button onClick={()=>resetFineTune(overlay.sceneIndex)} className="text-[11px] text-white/40 hover:text-white">Restaurar</button></div>{slider("Largura",overlay.widthPercent??84,36,92,value=>update(overlay.sceneIndex,{widthPercent:value}))}{slider("Escala",overlay.scalePercent??100,65,135,value=>update(overlay.sceneIndex,{scalePercent:value}))}{slider("Horizontal",overlay.offsetX??0,-28,28,value=>update(overlay.sceneIndex,{offsetX:value}),"")}{slider("Vertical",overlay.offsetY??0,-28,28,value=>update(overlay.sceneIndex,{offsetY:value}),"")}{slider("Fundo",overlay.panelOpacity??58,18,80,value=>update(overlay.sceneIndex,{panelOpacity:value}))}</div><label className="flex items-center gap-2 text-xs text-white/50"><input type="checkbox" checked={overlay.showBrand} disabled={composition.brand.mode==="none"} onChange={e=>update(overlay.sceneIndex,{showBrand:e.target.checked})}/> Exibir marca nesta cena</label><p className="text-[11px] leading-5 text-white/30">Base ativa: V{job?.version??1} · {job?.provider||"provider"}{job?.model?` · ${job.model}`:""}</p></div>
      </div></article>})}</div>
    <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-2 text-xs leading-5 text-white/35"><Sparkles className="mt-0.5 h-4 w-4 shrink-0"/><span>Os ajustes finos são salvos por cena e reproduzidos no render final.</span></div><div className="flex gap-2"><button onClick={()=>save(false)} disabled={!!busy} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-xs font-semibold text-white/65 disabled:opacity-40">{busy==="save"?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Save className="h-3.5 w-3.5"/>}Salvar</button><button onClick={()=>save(true)} disabled={!!busy} className="inline-flex items-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/[.07] px-4 py-2.5 text-xs font-semibold text-emerald-100 disabled:opacity-40">{busy==="approve"?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<CheckCircle2 className="h-3.5 w-3.5"/>}Aprovar composição</button></div></div>
  </section>;
}
