"use client";

import { useState } from "react";
import { CheckCircle2, Download, Film, Loader2, Play, ShieldCheck } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type FinalRender={state:string;format:"mp4";aspectRatio:string;transition:string;totalDurationSeconds:number;preparedAt:string;renderEngine:string;outputUrl?:string|null;sizeBytes?:number|null;error?:string|null};

export default function StudioFinalRenderPanel({projectId,composition,initialFinalRender}:{projectId:string;composition?:{state?:string}|null;initialFinalRender?:FinalRender|null}){
  const [manifest,setManifest]=useState<FinalRender|null>(initialFinalRender??null);
  const [busy,setBusy]=useState("");
  const [error,setError]=useState("");
  const approved=composition?.state==="approved";
  const prepared=manifest?.state==="prepared";
  const completed=manifest?.state==="completed";

  async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
  async function post(action:"prepare"|"render"){setBusy(action);setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/final-render`,{method:"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({action})});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.manifest){const base=payload.message||payload.error||"Não foi possível concluir a etapa.";const detail=payload.technicalDetail&&payload.technicalDetail!==payload.error?`\nDetalhe técnico: ${payload.technicalDetail}`:"";throw new Error(`${base}${detail}`);}setManifest(payload.manifest);}catch(e){setError(e instanceof Error?e.message:"Falha na montagem final.");}finally{setBusy("")}}
  async function download(){setBusy("download");setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/final-render/download`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.message||payload.error||"Não foi possível baixar o vídeo final.");}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="ALGENRI-Studio-Video-Final.mp4";document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Falha no download do vídeo final.");}finally{setBusy("")}}
  const sizeLabel=manifest?.sizeBytes?`${(manifest.sizeBytes/1024/1024).toFixed(1)} MB`:null;

  return <section className={`mt-8 rounded-[28px] border p-5 sm:p-6 ${approved?"border-violet-300/15 bg-violet-300/[.025]":"border-white/10 bg-white/[.02]"}`}>
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><Film className={`mt-0.5 h-5 w-5 ${approved?"text-violet-100":"text-white/35"}`}/><div><h2 className="text-lg font-semibold">Montagem final</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/45">Consolida as versões ativas, aplica as camadas exatas e gera um único MP4. Esta etapa usa processamento local do Studio e não consome novos créditos dos motores de IA.</p></div></div>{manifest&&<span className={`self-start rounded-full px-3 py-1.5 text-xs ${completed?"bg-emerald-300/10 text-emerald-100":manifest.state==="failed"?"bg-rose-300/10 text-rose-100":"bg-violet-300/10 text-violet-100"}`}>{completed?"MP4 concluído":manifest.state==="prepared"?"Pronto para renderizar":manifest.state==="rendering"?"Renderizando":"Atenção"}</span>}</div>

    {!approved&&<div className="mt-5 rounded-2xl border border-white/10 bg-black/15 p-4 text-sm text-white/40">Aprove primeiro a composição controlada para liberar a montagem final.</div>}
    {error&&<div className="mt-5 whitespace-pre-wrap rounded-2xl border border-rose-300/15 bg-rose-300/[.03] p-4 text-sm text-rose-100">{error}</div>}

    {manifest&&<div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Formato</p><p className="mt-2 font-semibold">MP4</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Proporção</p><p className="mt-2 font-semibold">{manifest.aspectRatio}</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Duração</p><p className="mt-2 font-semibold">{manifest.totalDurationSeconds}s</p></div><div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Saída</p><p className="mt-2 font-semibold">{completed?(sizeLabel||"Concluída"):prepared?"Aguardando render":"—"}</p></div></div>}

    {completed&&<div className="mt-5 flex items-start gap-3 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.035] p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-200"/><div><p className="text-sm font-semibold text-emerald-50">Vídeo final arquivado</p><p className="mt-1 text-xs leading-5 text-emerald-50/55">O MP4 foi salvo no armazenamento privado do projeto e já pode ser baixado.</p></div></div>}

    <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-2 text-xs leading-5 text-white/35"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><span>Renderização determinística: as cenas ativas e os textos aprovados são usados sem nova interpretação por IA.</span></div><div className="flex flex-wrap gap-2"><button onClick={()=>post("prepare")} disabled={!approved||!!busy} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-xs font-semibold text-white/65 disabled:cursor-not-allowed disabled:opacity-30">{busy==="prepare"?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Film className="h-3.5 w-3.5"/>}{manifest?"Repreparar":"Preparar montagem"}</button><button onClick={()=>post("render")} disabled={!prepared||!!busy} className="inline-flex items-center justify-center gap-2 rounded-xl border border-violet-300/20 bg-violet-300/[.08] px-4 py-2.5 text-xs font-semibold text-violet-100 disabled:cursor-not-allowed disabled:opacity-30">{busy==="render"?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Play className="h-3.5 w-3.5"/>}Renderizar MP4 final</button>{completed&&<button onClick={download} disabled={!!busy} className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/[.07] px-4 py-2.5 text-xs font-semibold text-emerald-100 disabled:opacity-40">{busy==="download"?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Download className="h-3.5 w-3.5"/>}Baixar MP4</button>}</div></div>
  </section>;
}
