"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Layers3, Loader2, Save, ShieldCheck, Sparkles } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Scene={index:number;title:string};
type Job={sceneIndex:number;version?:number;status:string;outputUrl?:string|null;provider?:string;model?:string|null};
type Overlay={sceneIndex:number;enabled:boolean;eyebrow:string;headline:string;body:string;cta:string;align:"left"|"center"|"right";position:"top"|"center"|"bottom";showBrand:boolean};
export type StudioCompositionClient={state:"draft"|"approved";sceneOverlays:Overlay[];transition:"cut"|"fade";approvedAt:string|null;updatedAt:string};

export default function StudioCompositionPanel({projectId,storyboard,generation,onCompositionChange}:{projectId:string;storyboard:Scene[];generation?:any;onCompositionChange?:(composition:StudioCompositionClient)=>void}){
 const [composition,setComposition]=useState<StudioCompositionClient|null>(null);const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const activeJobs=(generation?.sceneJobs??[]) as Job[];
 const ready=storyboard.length>0&&storyboard.every(scene=>activeJobs.some(job=>job.sceneIndex===scene.index&&job.status==="succeeded"));
 const jobByScene=useMemo(()=>new Map(activeJobs.map(job=>[job.sceneIndex,job])),[activeJobs]);
 async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
 async function load(){if(!ready)return;setBusy("load");setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/composition`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.composition)throw new Error(payload.error||"Não foi possível carregar a composição.");setComposition(payload.composition);onCompositionChange?.(payload.composition);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar composição.");}finally{setBusy("");}}
 useEffect(()=>{if(!ready)return;void load();},[ready,projectId]);
 function update(sceneIndex:number,patch:Partial<Overlay>){setComposition(current=>current?{...current,state:"draft",approvedAt:null,sceneOverlays:current.sceneOverlays.map(item=>item.sceneIndex===sceneIndex?{...item,...patch}:item)}:current);}
 async function save(approve=false){if(!composition)return;setBusy(approve?"approve":"save");setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/composition`,{method:"PATCH",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({sceneOverlays:composition.sceneOverlays,transition:composition.transition,approve})});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.composition)throw new Error(payload.error||"Não foi possível salvar a composição.");setComposition(payload.composition);onCompositionChange?.(payload.composition);}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar composição.");}finally{setBusy("");}}
 if(!ready)return <section className="mt-8 rounded-[28px] border border-white/10 bg-white/[.02] p-5 sm:p-6"><div className="flex gap-3"><Layers3 className="mt-0.5 h-5 w-5 text-white/40"/><div><h2 className="text-lg font-semibold">Composição controlada</h2><p className="mt-2 text-sm leading-6 text-white/40">Disponível quando todas as cenas tiverem uma versão ativa concluída. Esta etapa aplica textos e marca exatos sem depender do gerador de vídeo.</p></div></div></section>;
 if(busy==="load"&&!composition)return <section className="mt-8 rounded-[28px] border border-cyan-300/15 bg-cyan-300/[.02] p-5 text-sm text-white/50"><Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>Carregando composição...</section>;
 if(!composition)return null;
 return <section className="mt-8 rounded-[28px] border border-cyan-300/15 bg-cyan-300/[.025] p-5 sm:p-6">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-cyan-100"/><div><h2 className="text-lg font-semibold">Composição controlada</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/45">As cenas geradas ficam como base visual. ALGENRI, títulos e CTA são aplicados aqui como camadas exatas e editáveis. O gerador não recebe mais a responsabilidade de escrever a marca.</p></div></div><span className={`self-start rounded-full px-3 py-1.5 text-xs ${composition.state==="approved"?"bg-emerald-300/10 text-emerald-100":"bg-amber-300/10 text-amber-100"}`}>{composition.state==="approved"?"Composição aprovada":"Rascunho"}</span></div>
  {error&&<div className="mt-4 rounded-2xl border border-rose-300/15 bg-rose-300/[.03] p-4 text-sm text-rose-100">{error}</div>}
  <div className="mt-5 flex flex-wrap items-center gap-3"><label className="text-xs text-white/45">Transição entre cenas</label><select value={composition.transition} onChange={e=>setComposition({...composition,state:"draft",approvedAt:null,transition:e.target.value as "cut"|"fade"})} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-sm"><option value="fade">Fade suave</option><option value="cut">Corte direto</option></select></div>
  <div className="mt-6 space-y-5">{composition.sceneOverlays.map(overlay=>{const scene=storyboard.find(item=>item.index===overlay.sceneIndex);const job=jobByScene.get(overlay.sceneIndex);return <article key={overlay.sceneIndex} className="rounded-[24px] border border-white/10 bg-black/15 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.12em] text-cyan-200/60">Cena {overlay.sceneIndex}</p><h3 className="mt-1 font-semibold">{scene?.title||`Cena ${overlay.sceneIndex}`}</h3></div><label className="flex items-center gap-2 text-xs text-white/50"><input type="checkbox" checked={overlay.enabled} onChange={e=>update(overlay.sceneIndex,{enabled:e.target.checked})}/> Exibir camadas</label></div>
   <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#07111f] aspect-video">{job?.outputUrl?<video src={job.outputUrl} muted playsInline controls className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-white/30">Prévia da cena indisponível</div>}{overlay.enabled&&<div className={`pointer-events-none absolute inset-0 flex p-[6%] ${overlay.position==="top"?"items-start":overlay.position==="bottom"?"items-end":"items-center"} ${overlay.align==="center"?"justify-center text-center":overlay.align==="right"?"justify-end text-right":"justify-start text-left"}`}><div className="max-w-[72%] rounded-2xl bg-black/35 p-4 backdrop-blur-[2px]">{overlay.showBrand&&<div className="text-[clamp(10px,1.2vw,16px)] font-bold tracking-[.18em] text-cyan-100">ALGENRI</div>}{overlay.eyebrow&&<div className="mt-2 text-[clamp(9px,1vw,13px)] uppercase tracking-[.14em] text-white/70">{overlay.eyebrow}</div>}{overlay.headline&&<div className="mt-2 text-[clamp(16px,2.4vw,34px)] font-semibold leading-tight text-white">{overlay.headline}</div>}{overlay.body&&<div className="mt-2 text-[clamp(10px,1.2vw,15px)] leading-relaxed text-white/80">{overlay.body}</div>}{overlay.cta&&<div className="mt-3 inline-flex rounded-full border border-cyan-100/40 bg-cyan-100/10 px-3 py-1.5 text-[clamp(9px,1vw,13px)] font-semibold text-cyan-50">{overlay.cta}</div>}</div></div>}</div>
    <div className="grid gap-3"><input value={overlay.eyebrow} onChange={e=>update(overlay.sceneIndex,{eyebrow:e.target.value})} placeholder="Chamada curta" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><input value={overlay.headline} onChange={e=>update(overlay.sceneIndex,{headline:e.target.value})} placeholder="Título exato" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><textarea value={overlay.body} onChange={e=>update(overlay.sceneIndex,{body:e.target.value})} rows={3} placeholder="Texto complementar" className="resize-y rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><input value={overlay.cta} onChange={e=>update(overlay.sceneIndex,{cta:e.target.value})} placeholder="CTA" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none"/><div className="grid grid-cols-2 gap-3"><select value={overlay.position} onChange={e=>update(overlay.sceneIndex,{position:e.target.value as Overlay["position"]})} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm"><option value="top">Topo</option><option value="center">Centro</option><option value="bottom">Rodapé</option></select><select value={overlay.align} onChange={e=>update(overlay.sceneIndex,{align:e.target.value as Overlay["align"]})} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm"><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></div><label className="flex items-center gap-2 text-xs text-white/50"><input type="checkbox" checked={overlay.showBrand} onChange={e=>update(overlay.sceneIndex,{showBrand:e.target.checked})}/> Exibir marca ALGENRI exata</label><p className="text-[11px] leading-5 text-white/30">Base ativa: V{job?.version??1} · {job?.provider||"provider"}{job?.model?` · ${job.model}`:""}</p></div></div>
  </article>})}</div>
  <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-2 text-xs leading-5 text-white/35"><Sparkles className="mt-0.5 h-4 w-4 shrink-0"/><span>Ao aprovar, esta configuração fica pronta para a etapa seguinte: montagem e renderização do MP4 final.</span></div><div className="flex gap-2"><button onClick={()=>save(false)} disabled={!!busy} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-xs font-semibold text-white/65 disabled:opacity-40">{busy==="save"?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Save className="h-3.5 w-3.5"/>}Salvar</button><button onClick={()=>save(true)} disabled={!!busy} className="inline-flex items-center gap-2 rounded-xl border border-emerald-300/20 bg-emerald-300/[.07] px-4 py-2.5 text-xs font-semibold text-emerald-100 disabled:opacity-40">{busy==="approve"?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<CheckCircle2 className="h-3.5 w-3.5"/>}Aprovar composição</button></div></div>
 </section>;
}
