"use client";

import { useEffect,useMemo,useState } from "react";
import { BookOpen,Lock,Plus,Save,Trash2,Unlock } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Character={id:string;name:string;role:string;description:string;wardrobe:string;behavior:string;locked:boolean};
type Environment={id:string;name:string;description:string;lighting:string;camera:string;locked:boolean};
type Bible={characters:Character[];environments:Environment[];globalVisualRules:string;continuityNotes:string;updatedAt?:string|null};
const empty:Bible={characters:[],environments:[],globalVisualRules:"",continuityNotes:""};
const input="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/20";
const area=`${input} resize-y leading-6`;
function id(prefix:string){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}

export default function StudioVisualBiblePanel({projectId,initialValue,onChange}:{projectId:string;initialValue?:Partial<Bible>|null;onChange?:(value:Bible)=>void}){
 const [value,setValue]=useState<Bible>({...empty,...(initialValue||{}),characters:initialValue?.characters??[],environments:initialValue?.environments??[]});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[dirty,setDirty]=useState(false);const[loading,setLoading]=useState(!initialValue);
 const lockedCharacters=useMemo(()=>value.characters.filter(x=>x.locked).length,[value.characters]);const lockedEnvironments=useMemo(()=>value.environments.filter(x=>x.locked).length,[value.environments]);
 async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
 useEffect(()=>{if(initialValue){setValue({...empty,...initialValue,characters:initialValue.characters??[],environments:initialValue.environments??[]});setLoading(false);return;}let active=true;(async()=>{try{const response=await fetch(`/api/internal/studio/projects/${projectId}/visual-bible`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));if(active&&response.ok&&payload.visualBible)setValue({...empty,...payload.visualBible});}catch{}finally{if(active)setLoading(false);}})();return()=>{active=false};},[projectId]);
 function patch(next:Partial<Bible>){setValue(current=>({...current,...next}));setDirty(true);}
 function patchCharacter(index:number,next:Partial<Character>){patch({characters:value.characters.map((item,i)=>i===index?{...item,...next}:item)});}
 function patchEnvironment(index:number,next:Partial<Environment>){patch({environments:value.environments.map((item,i)=>i===index?{...item,...next}:item)});}
 async function save(){setBusy(true);setError("");try{const response=await fetch(`/api/internal/studio/projects/${projectId}/visual-bible`,{method:"PATCH",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify(value)});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload.visualBible)throw new Error(payload.error||"Não foi possível salvar a bíblia visual.");setValue(payload.visualBible);setDirty(false);onChange?.(payload.visualBible);}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar a bíblia visual.");}finally{setBusy(false);}}
 return <section className="mt-8 rounded-[28px] border border-fuchsia-300/15 bg-fuchsia-300/[.025] p-5 sm:p-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><BookOpen className="mt-0.5 h-5 w-5 text-fuchsia-100"/><div><h2 className="text-lg font-semibold">Bíblia visual do projeto</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-white/45">Cadastre personagens e ambientes que devem ser reutilizados. Itens bloqueados passam a fazer parte das restrições de continuidade e do contexto usado pela IA ao regenerar cenas.</p></div></div><div className="flex gap-2 text-[10px] text-white/35"><span className="rounded-full border border-white/10 px-2.5 py-1">{lockedCharacters} personagens fixos</span><span className="rounded-full border border-white/10 px-2.5 py-1">{lockedEnvironments} ambientes fixos</span></div></div>
  {error&&<div className="mt-4 rounded-2xl border border-rose-300/15 bg-rose-300/[.04] p-4 text-sm text-rose-100">{error}</div>}
  {loading?<div className="mt-5 rounded-2xl border border-white/10 bg-black/15 p-4 text-xs text-white/35">Carregando bíblia visual...</div>:<>
  <div className="mt-5 grid gap-5 xl:grid-cols-2">
   <div className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">Personagens</p><p className="mt-1 text-xs text-white/35">Principal e secundários recorrentes.</p></div><button onClick={()=>patch({characters:[...value.characters,{id:id("char"),name:"Novo personagem",role:"",description:"",wardrobe:"",behavior:"",locked:true}]})} className="inline-flex items-center gap-2 rounded-xl border border-fuchsia-300/15 px-3 py-2 text-xs text-fuchsia-100"><Plus className="h-3.5 w-3.5"/>Adicionar</button></div>
    <div className="mt-4 space-y-3">{value.characters.length===0?<div className="rounded-xl border border-dashed border-white/10 p-4 text-xs text-white/30">Nenhum personagem estruturado. A continuidade textual atual continua válida.</div>:value.characters.map((item,index)=><div key={item.id} className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="flex items-center gap-2"><input value={item.name} onChange={e=>patchCharacter(index,{name:e.target.value})} className={input} placeholder="Nome / identificador"/><button title={item.locked?"Desbloquear":"Bloquear na continuidade"} onClick={()=>patchCharacter(index,{locked:!item.locked})} className={`rounded-xl border p-2.5 ${item.locked?"border-emerald-300/20 text-emerald-100":"border-white/10 text-white/35"}`}>{item.locked?<Lock className="h-4 w-4"/>:<Unlock className="h-4 w-4"/>}</button><button onClick={()=>patch({characters:value.characters.filter((_,i)=>i!==index)})} className="rounded-xl border border-rose-300/15 p-2.5 text-rose-100"><Trash2 className="h-4 w-4"/></button></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={item.role} onChange={e=>patchCharacter(index,{role:e.target.value})} className={input} placeholder="Papel: protagonista, cliente..."/><input value={item.wardrobe} onChange={e=>patchCharacter(index,{wardrobe:e.target.value})} className={input} placeholder="Figurino / aparência"/></div><textarea rows={3} value={item.description} onChange={e=>patchCharacter(index,{description:e.target.value})} className={`${area} mt-3`} placeholder="Características visuais que precisam permanecer iguais."/><textarea rows={2} value={item.behavior} onChange={e=>patchCharacter(index,{behavior:e.target.value})} className={`${area} mt-3`} placeholder="Postura, energia, expressão e comportamento recorrente."/></div>)}</div>
   </div>
   <div className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">Ambientes</p><p className="mt-1 text-xs text-white/35">Locações e linguagem de câmera recorrentes.</p></div><button onClick={()=>patch({environments:[...value.environments,{id:id("env"),name:"Novo ambiente",description:"",lighting:"",camera:"",locked:true}]})} className="inline-flex items-center gap-2 rounded-xl border border-cyan-300/15 px-3 py-2 text-xs text-cyan-100"><Plus className="h-3.5 w-3.5"/>Adicionar</button></div>
    <div className="mt-4 space-y-3">{value.environments.length===0?<div className="rounded-xl border border-dashed border-white/10 p-4 text-xs text-white/30">Nenhum ambiente estruturado. Você pode adicionar apenas quando a locação precisar permanecer consistente.</div>:value.environments.map((item,index)=><div key={item.id} className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="flex items-center gap-2"><input value={item.name} onChange={e=>patchEnvironment(index,{name:e.target.value})} className={input} placeholder="Nome do ambiente"/><button onClick={()=>patchEnvironment(index,{locked:!item.locked})} className={`rounded-xl border p-2.5 ${item.locked?"border-emerald-300/20 text-emerald-100":"border-white/10 text-white/35"}`}>{item.locked?<Lock className="h-4 w-4"/>:<Unlock className="h-4 w-4"/>}</button><button onClick={()=>patch({environments:value.environments.filter((_,i)=>i!==index)})} className="rounded-xl border border-rose-300/15 p-2.5 text-rose-100"><Trash2 className="h-4 w-4"/></button></div><textarea rows={3} value={item.description} onChange={e=>patchEnvironment(index,{description:e.target.value})} className={`${area} mt-3`} placeholder="Arquitetura, materiais, objetos e paleta."/><div className="mt-3 grid gap-3 sm:grid-cols-2"><textarea rows={2} value={item.lighting} onChange={e=>patchEnvironment(index,{lighting:e.target.value})} className={area} placeholder="Iluminação / hora do dia"/><textarea rows={2} value={item.camera} onChange={e=>patchEnvironment(index,{camera:e.target.value})} className={area} placeholder="Lente, enquadramento e movimento"/></div></div>)}</div>
   </div>
  </div>
  <div className="mt-5 grid gap-4 lg:grid-cols-2"><label className="rounded-2xl border border-white/10 bg-black/15 p-4 text-xs text-white/45">Regras visuais globais<textarea rows={4} value={value.globalVisualRules} onChange={e=>patch({globalVisualRules:e.target.value})} className={`${area} mt-3`} placeholder="Paleta, contraste, profundidade, ritmo, realismo, textura..."/></label><label className="rounded-2xl border border-white/10 bg-black/15 p-4 text-xs text-white/45">Notas de continuidade<textarea rows={4} value={value.continuityNotes} onChange={e=>patch({continuityNotes:e.target.value})} className={`${area} mt-3`} placeholder="O que nunca pode mudar ou ser duplicado entre as cenas."/></label></div>
  <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-white/30">Salvar invalida o roteamento para que o próximo cálculo considere a nova bíblia visual. Não gera vídeo nem consome créditos.</p><button onClick={save} disabled={busy||!dirty} className="inline-flex items-center justify-center gap-2 rounded-xl border border-fuchsia-300/20 bg-fuchsia-300/[.07] px-4 py-2.5 text-xs font-semibold text-fuchsia-100 disabled:opacity-35"><Save className="h-3.5 w-3.5"/>{busy?"Salvando...":"Salvar bíblia visual"}</button></div></>}
 </section>;
}
