"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Boxes, CheckCircle2, Layers3, Plus, Save } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Kind="asset"|"character"|"environment"|"brandPreset"|"template";
type Item={id?:string;kind:Kind;name:string;description:string;tags:string[];sourceUrl?:string;storagePath?:string;metadata:Record<string,any>;isDefault:boolean;locked:boolean};
const labels:Record<Kind,string>={asset:"Asset",character:"Personagem",environment:"Ambiente",brandPreset:"Preset de marca",template:"Template"};
const blank:Item={kind:"asset",name:"",description:"",tags:[],metadata:{},isDefault:false,locked:false};
const box="rounded-[24px] border border-white/10 bg-white/[.025] p-5";const input="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none focus:border-cyan-300/25";

export default function StudioCreativeLibraryPage(){
 const [items,setItems]=useState<Item[]>([]);const [form,setForm]=useState<Item>(blank);const [tagText,setTagText]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 const canSave=useMemo(()=>form.name.trim().length>=2,[form.name]);
 async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
 async function load(){setLoading(true);setMessage("");try{const response=await fetch("/api/internal/studio/creative-library",{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Falha ao carregar biblioteca.");setItems(payload.items||[]);}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar biblioteca.");}finally{setLoading(false)}}
 useEffect(()=>{const unsub=firebaseAuth.onAuthStateChanged(user=>{if(user)void load();else setLoading(false)});return unsub;},[]);
 async function save(){if(!canSave)return;setSaving(true);setMessage("");try{const response=await fetch("/api/internal/studio/creative-library",{method:"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({...form,tags:tagText.split(",").map(x=>x.trim()).filter(Boolean)})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Falha ao salvar item.");setForm(blank);setTagText("");setMessage("Item salvo na Biblioteca Criativa.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Falha ao salvar item.");}finally{setSaving(false)}}
 function edit(item:Item){setForm(item);setTagText(item.tags.join(", "));window.scrollTo({top:0,behavior:"smooth"});}
 return <main className="min-h-screen bg-[#040c17] px-5 pb-24 pt-24 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
  <a href="/interno/lab/studio" className="inline-flex items-center gap-2 text-xs text-white/45"><ArrowLeft className="h-4 w-4"/>Voltar ao Studio</a>
  <header className="mt-5 border-b border-white/10 pb-7"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-200"><Boxes className="h-4 w-4"/>ALGENRI Studio · Biblioteca Criativa</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Assets, personagens, ambientes, marcas e templates</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-white/50">Uma base única para reutilizar referências aprovadas entre projetos, reduzir retrabalho e preservar consistência visual.</p></header>
  <section className="mt-7 grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><div className={box}><div className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-violet-200"/><h2 className="font-semibold">{form.id?"Editar item":"Novo item"}</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs text-white/50">Tipo<select className={input} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as Kind})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs text-white/50">Nome<input className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div><label className="mt-4 block text-xs text-white/50">Descrição<textarea rows={4} className={input} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="mt-4 block text-xs text-white/50">Tags<input className={input} value={tagText} onChange={e=>setTagText(e.target.value)} placeholder="institucional, premium, escritório, personagem..."/></label><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-xs text-white/50">URL/referência<input className={input} value={form.sourceUrl||""} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></label><label className="text-xs text-white/50">Storage path<input className={input} value={form.storagePath||""} onChange={e=>setForm({...form,storagePath:e.target.value})}/></label></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3 text-xs text-white/55"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/>Usar como padrão deste tipo</label><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3 text-xs text-white/55"><input type="checkbox" checked={form.locked} onChange={e=>setForm({...form,locked:e.target.checked})}/>Bloquear como referência aprovada</label></div><div className="mt-5 flex gap-2"><button disabled={!canSave||saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/[.08] px-4 py-3 text-sm font-semibold text-cyan-100 disabled:opacity-40"><Save className="h-4 w-4"/>{saving?"Salvando...":"Salvar"}</button><button onClick={()=>{setForm(blank);setTagText("")}} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/55"><Plus className="h-4 w-4"/>Novo</button></div>{message&&<p className="mt-4 text-xs text-emerald-200">{message}</p>}</div>
  <div className={box}><h2 className="font-semibold">Itens reutilizáveis</h2><p className="mt-2 text-xs text-white/40">Personagens e ambientes podem alimentar a Bíblia Visual; presets de marca e templates aceleram novas produções.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{loading?<p className="text-xs text-white/35">Carregando...</p>:items.length===0?<p className="text-xs text-white/35">Nenhum item cadastrado.</p>:items.map(item=><button key={item.id} onClick={()=>edit(item)} className="rounded-2xl border border-white/10 bg-white/[.02] p-4 text-left hover:border-cyan-300/20"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.12em] text-cyan-200/60">{labels[item.kind]}</p><p className="mt-1 font-semibold">{item.name}</p></div>{item.isDefault&&<CheckCircle2 className="h-4 w-4 text-emerald-200"/>}</div><p className="mt-3 line-clamp-3 text-xs leading-5 text-white/45">{item.description||"Sem descrição."}</p><div className="mt-3 flex flex-wrap gap-1.5">{item.tags.slice(0,4).map(tag=><span key={tag} className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-white/35">{tag}</span>)}</div></button>)}</div></div></section>
 </div></main>;
}
