"use client";

import { useState } from "react";
import { Loader2, Mic2, Play, Volume2 } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

const field="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none placeholder:text-white/20";
export default function StudioVoiceLabPage(){
 const[provider,setProvider]=useState<"elevenlabs"|"minimax">("elevenlabs");const[text,setText]=useState("Olá. Este é um teste de voz do ALGENRI Studio.");const[voiceId,setVoiceId]=useState("");const[model,setModel]=useState("");const[speed,setSpeed]=useState(1);const[emotion,setEmotion]=useState("neutral");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[audioUrl,setAudioUrl]=useState("");
 async function token(){const user=firebaseAuth.currentUser;if(!user)throw new Error("Sessão não encontrada.");return user.getIdToken();}
 async function preview(){setBusy(true);setError("");try{const response=await fetch("/api/internal/studio/voice/preview",{method:"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify({provider,text,voiceId,...(model.trim()?{model:model.trim()}:{}) ,speed,...(provider==="minimax"?{emotion}:{})})});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.error||"Não foi possível gerar a prévia.");}const blob=await response.blob();const url=URL.createObjectURL(blob);setAudioUrl(old=>{if(old)URL.revokeObjectURL(old);return url;});}catch(e){setError(e instanceof Error?e.message:"Falha ao gerar prévia.");}finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#040c17] px-6 pb-20 pt-28 text-white"><div className="mx-auto max-w-5xl"><header className="border-b border-white/10 pb-7"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-200"><Mic2 className="h-4 w-4"/>ALGENRI Studio · Voice Lab</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Comparador de voz neural</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-white/50">Teste ElevenLabs e MiniMax com trechos curtos antes de gerar locuções completas. Cada clique pode consumir créditos do provedor escolhido.</p></header>
 <section className="mt-7 rounded-[28px] border border-white/10 bg-white/[.02] p-5 sm:p-6"><div className="grid gap-4 md:grid-cols-2"><label className="text-xs text-white/45">Provedor<select className={`${field} mt-2`} value={provider} onChange={e=>setProvider(e.target.value as any)}><option value="elevenlabs">ElevenLabs</option><option value="minimax">MiniMax Audio</option></select></label><label className="text-xs text-white/45">Voice ID<input className={`${field} mt-2`} value={voiceId} onChange={e=>setVoiceId(e.target.value)} placeholder="Cole o ID da voz"/></label><label className="text-xs text-white/45">Modelo opcional<input className={`${field} mt-2`} value={model} onChange={e=>setModel(e.target.value)} placeholder={provider==="elevenlabs"?"eleven_multilingual_v2":"speech-2.8-hd"}/></label><label className="text-xs text-white/45">Velocidade: {speed.toFixed(2)}<input type="range" min="0.5" max="2" step="0.05" value={speed} onChange={e=>setSpeed(Number(e.target.value))} className="mt-3 w-full"/></label>{provider==="minimax"&&<label className="text-xs text-white/45">Emoção<select className={`${field} mt-2`} value={emotion} onChange={e=>setEmotion(e.target.value)}><option value="neutral">Neutral</option><option value="happy">Happy</option><option value="sad">Sad</option><option value="angry">Angry</option><option value="fearful">Fearful</option><option value="disgusted">Disgusted</option><option value="surprised">Surprised</option></select></label>}<label className="text-xs text-white/45 md:col-span-2">Texto de teste<textarea rows={6} className={`${field} mt-2 resize-y leading-6`} value={text} onChange={e=>setText(e.target.value)} maxLength={1200}/><span className="mt-1 block text-[10px] text-white/25">Use trechos curtos para comparar qualidade e custo antes da locução final.</span></label></div>{error&&<div className="mt-4 rounded-2xl border border-rose-300/15 bg-rose-300/[.04] p-4 text-sm text-rose-100">{error}</div>}<div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-white/30">Nenhuma geração acontece automaticamente.</p><button onClick={preview} disabled={busy||!voiceId.trim()||!text.trim()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/[.07] px-4 py-2.5 text-sm font-semibold text-cyan-100 disabled:opacity-35">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Play className="h-4 w-4"/>}Gerar prévia</button></div>{audioUrl&&<div className="mt-5 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.025] p-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-emerald-100"><Volume2 className="h-4 w-4"/>Prévia gerada</div><audio controls src={audioUrl} className="w-full"/></div>}</section>
 </div></main>;
}
