"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Loader2, Route, ShieldCheck, TriangleAlert } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type GovernancePayload={policyVersion:string;routing?:any;providerUsage?:Record<string,{jobs:number;credits:number}>;events?:Array<any>};

export default function StudioGovernancePage({params}:{params:Promise<{projectId:string}>}){
  const [projectId,setProjectId]=useState("");const[data,setData]=useState<GovernancePayload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{params.then(v=>setProjectId(v.projectId));},[params]);
  useEffect(()=>{if(!projectId)return;const unsub=firebaseAuth.onAuthStateChanged(async user=>{if(!user){setLoading(false);return;}try{setLoading(true);const response=await fetch(`/api/internal/studio/projects/${projectId}/governance`,{headers:{Authorization:`Bearer ${await user.getIdToken()}`},cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Não foi possível carregar a governança.");setData(payload);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar a governança.");}finally{setLoading(false);}});return unsub;},[projectId]);
  const routes=data?.routing?.routes??[];const usage=Object.entries(data?.providerUsage??{});
  return <main className="min-h-screen bg-[#040c17] px-5 pb-24 pt-24 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
    <a href={`/interno/lab/studio/projetos/${projectId}`} className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft className="h-4 w-4"/>Voltar ao projeto</a>
    <header className="mt-5 border-b border-white/10 pb-7"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-cyan-200"><ShieldCheck className="h-4 w-4"/>ALGENRI Studio · Governança</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Decisões, custos e auditoria</h1><p className="mt-3 max-w-4xl text-sm leading-6 text-white/50">Rastreabilidade das regras de roteamento, provedores, prompts técnicos, custos e decisões registradas pelo Studio.</p></header>
    {loading&&<div className="mt-7 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.02] p-5 text-sm text-white/45"><Loader2 className="h-4 w-4 animate-spin"/>Carregando governança...</div>}
    {error&&<div className="mt-7 flex gap-3 rounded-2xl border border-rose-300/15 bg-rose-300/[.03] p-5 text-sm text-rose-100"><TriangleAlert className="h-5 w-5"/>{error}</div>}
    {data&&<><section className="mt-7 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Política</p><p className="mt-2 font-semibold">{data.policyVersion}</p></div><div className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Rotas atuais</p><p className="mt-2 font-semibold">{routes.length}</p></div><div className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><p className="text-[10px] uppercase tracking-[.12em] text-white/25">Eventos auditados</p><p className="mt-2 font-semibold">{data.events?.length??0}</p></div></section>
    <section className="mt-7 rounded-[26px] border border-white/10 bg-white/[.02] p-5"><div className="flex items-center gap-2"><Route className="h-5 w-5 text-cyan-200"/><h2 className="font-semibold">Decisão de roteamento atual</h2></div><div className="mt-4 space-y-3">{routes.length?routes.map((route:any)=><article key={route.sceneIndex} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.12em] text-cyan-200/60">Cena {route.sceneIndex}</p><p className="mt-1 font-semibold">{route.selectedProviderName}{route.selectedModel?` · ${route.selectedModel}`:""}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/55">score {route.winnerScore??"—"}{route.scoreMargin!=null?` · margem ${route.scoreMargin}`:""}</span></div><p className="mt-2 text-xs leading-5 text-white/40">{route.reason}</p></article>):<p className="text-sm text-white/35">Nenhum roteamento calculado ainda.</p>}</div></section>
    <section className="mt-7 rounded-[26px] border border-white/10 bg-white/[.02] p-5"><h2 className="font-semibold">Uso por provedor</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{usage.length?usage.map(([provider,v])=><div key={provider} className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="font-semibold capitalize">{provider}</p><p className="mt-2 text-xs text-white/40">{v.jobs} job(s) · {v.credits} créditos reais</p></div>):<p className="text-sm text-white/35">Nenhum consumo registrado.</p>}</div></section>
    <section className="mt-7 rounded-[26px] border border-white/10 bg-white/[.02] p-5"><h2 className="font-semibold">Histórico de auditoria</h2><div className="mt-4 space-y-3">{(data.events??[]).length?(data.events??[]).map((event:any)=><article key={event.id} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold">{event.summary}</p><span className="text-[11px] text-white/30">{event.createdAt?new Date(event.createdAt).toLocaleString("pt-BR"):"—"}</span></div><p className="mt-2 text-[11px] uppercase tracking-[.1em] text-white/25">{event.type}{event.source?` · ${event.source}`:""}</p>{event.details&&<details className="mt-3"><summary className="cursor-pointer text-xs text-cyan-100/70">Ver snapshot técnico</summary><pre className="mt-3 overflow-x-auto whitespace-pre-wrap rounded-xl border border-white/10 bg-black/25 p-3 text-[11px] leading-5 text-white/45">{JSON.stringify(event.details,null,2)}</pre></details>}</article>):<p className="text-sm text-white/35">O histórico começará a ser preenchido nas próximas decisões do Studio.</p>}</div></section></>}
  </div></main>;
}
