"use client";

import { useEffect,useState } from "react";
import { onAuthStateChanged,type User } from "firebase/auth";
import { ArrowLeft,FileDown,Save,Upload } from "lucide-react";
import { firebaseAuth } from "@/lib/firebase/client";

type Party={legalName:string;tradeName?:string;taxId:string;address:string;representative:string};
type Clause={title:string;content:string};
type Contract={id:string;contractNumber:string;status:string;title:string;startDate:string;endDate:string;notes:string;signedFileName:string|null;proposalNumber:string;proposalVersion:string;clientName:string;projectName:string};
type DocumentData={contract:Contract;contractor:Party;contracting:Party;clauses:Clause[];operationalNotice:string};
const labels:Record<string,string>={draft:"Em elaboração",awaiting_signature:"Aguardando assinatura",signed:"Assinado",cancelled:"Cancelado"};

async function authFetch(user:User,url:string,init?:RequestInit){const token=await user.getIdToken();return fetch(url,{...init,headers:{...(init?.headers??{}),Authorization:`Bearer ${token}`}})}

export default function ContractDetailAdmin({id}:{id:string}){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[data,setData]=useState<DocumentData|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setUser(u);setReady(true)}),[]);
 async function load(u=user){if(!u)return;const r=await authFetch(u,`/api/internal/contracts/${id}/document`);const p=await r.json();if(!r.ok)throw new Error("Não foi possível gerar a visualização do contrato.");setData(p.document)}
 useEffect(()=>{if(user)load(user).catch(e=>setMessage(e.message))},[user,id]);
 async function save(){if(!user||!data||busy)return;setBusy(true);const c=data.contract;const r=await authFetch(user,`/api/internal/contracts/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:c.title,startDate:c.startDate,endDate:c.endDate,notes:c.notes})});setBusy(false);if(!r.ok){setMessage("Não foi possível salvar os dados do contrato.");return;}await load(user);setMessage("Dados do contrato atualizados.")}
 async function changeStatus(status:string){if(!user||!data)return;const r=await authFetch(user,`/api/internal/contracts/${id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const p=await r.json();if(!r.ok){setMessage(p.error==="signed_file_required"?"Faça upload do PDF assinado antes de marcar como Assinado.":"Não foi possível alterar o status.");return;}await load(user);setMessage(`Contrato atualizado para ${labels[status]||status}.`)}
 async function upload(file:File){if(!user)return;setBusy(true);const form=new FormData();form.append("file",file);const r=await authFetch(user,`/api/internal/contracts/${id}/signed-file`,{method:"POST",body:form});const p=await r.json();setBusy(false);if(!r.ok){setMessage(p.error==="pdf_required"?"Envie o contrato assinado em PDF.":"Não foi possível armazenar o contrato assinado.");return;}await load(user);setMessage("PDF assinado armazenado. Agora o contrato pode ser marcado como Assinado.")}
 function updateContract(patch:Partial<Contract>){if(!data)return;setData({...data,contract:{...data.contract,...patch}})}
 if(!ready)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Carregando…</main>;if(!user)return <main className="min-h-screen bg-[#040c17] grid place-items-center text-white">Faça login em /interno.</main>;if(!data)return <main className="min-h-screen bg-[#040c17] grid place-items-center px-6 text-center text-white">{message||"Preparando contrato…"}</main>;
 const c=data.contract;const locked=c.status==="signed"||c.status==="cancelled";const input="rounded-xl border border-white/10 bg-[#071423] px-3 py-2.5 text-sm text-white outline-none disabled:opacity-50";
 return <main className="min-h-screen bg-[#040c17] px-6 py-10 text-white"><div className="mx-auto max-w-6xl">
  <a href="/interno/contratos" className="inline-flex items-center gap-2 text-sm text-white/50"><ArrowLeft size={15}/>Contratos</a>
  <div className="mt-6 flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-semibold tracking-[.2em] text-cyan-300">{c.contractNumber}</p><h1 className="mt-2 text-3xl font-semibold">{c.title}</h1><p className="mt-2 text-sm text-white/45">{c.clientName} — {c.projectName} · origem {c.proposalNumber} v{c.proposalVersion}</p><p className="mt-2 text-xs text-emerald-200">{labels[c.status]||c.status}</p></div><div className="flex flex-wrap gap-2 print:hidden">{!locked&&<button disabled={busy} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950"><Save size={15}/>Salvar</button>}<button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-4 py-2.5 text-sm"><FileDown size={15}/>Imprimir / Salvar PDF</button></div></div>
  <section className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-5 md:grid-cols-2 print:hidden"><input disabled={locked} className={input} type="date" value={c.startDate||""} onChange={e=>updateContract({startDate:e.target.value})}/><input disabled={locked} className={input} type="date" value={c.endDate||""} onChange={e=>updateContract({endDate:e.target.value})}/><textarea disabled={locked} className={`${input} min-h-20 md:col-span-2`} value={c.notes||""} onChange={e=>updateContract({notes:e.target.value})} placeholder="Observações internas do contrato"/></section>
  <section className="mt-6 flex flex-wrap gap-2 print:hidden">{c.status==="draft"&&<button onClick={()=>changeStatus("awaiting_signature")} className="rounded-xl border border-violet-300/25 px-4 py-2.5 text-sm text-violet-100">Preparar para assinatura</button>}{!locked&&<label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-violet-300/25 px-4 py-2.5 text-sm text-violet-100"><Upload size={15}/>{busy?"Enviando…":"Upload contrato assinado"}<input type="file" accept="application/pdf" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>}{c.signedFileName&&!locked&&<button onClick={()=>changeStatus("signed")} className="rounded-xl bg-emerald-300 px-4 py-2.5 text-sm font-semibold text-slate-950">Marcar como assinado</button>}</section>
  {message&&<p className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.04] px-4 py-3 text-sm text-amber-100 print:hidden">{message}</p>}
  <div className="mt-8 rounded-2xl border border-amber-300/15 bg-amber-300/[.04] p-4 text-sm text-amber-100/80 print:hidden">{data.operationalNotice}</div>
  <article className="contract-paper mx-auto mt-8 max-w-[850px] bg-white px-10 py-12 text-slate-900 shadow-2xl print:mt-0 print:max-w-none print:shadow-none">
   <div className="border-b border-slate-200 pb-6 text-center"><p className="text-xs font-bold tracking-[.25em] text-slate-500">ALGENRI</p><h2 className="mt-2 text-2xl font-bold">CONTRATO DE PRESTAÇÃO DE SERVIÇOS</h2><p className="mt-2 text-sm text-slate-500">{c.contractNumber} · Proposta {c.proposalNumber} v{c.proposalVersion}</p></div>
   <div className="mt-7 space-y-4 text-sm leading-6"><p><strong>CONTRATADA:</strong> {data.contractor.legalName}, CNPJ {data.contractor.taxId}, com endereço em {data.contractor.address}, representada por {data.contractor.representative}.</p><p><strong>CONTRATANTE:</strong> {data.contracting.legalName}{data.contracting.tradeName?` (${data.contracting.tradeName})`:""}, CNPJ/CPF {data.contracting.taxId}, com referência de endereço em {data.contracting.address}, representada por {data.contracting.representative}.</p></div>
   <div className="mt-8 space-y-7">{data.clauses.map(clause=><section key={clause.title}><h3 className="text-sm font-bold uppercase tracking-wide">{clause.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{clause.content}</p></section>)}</div>
   <div className="mt-12 grid gap-10 text-sm md:grid-cols-2"><div><div className="border-t border-slate-400 pt-2">CONTRATANTE — {data.contracting.legalName}</div><p className="mt-2 text-xs text-slate-500">Representante: {data.contracting.representative}</p></div><div><div className="border-t border-slate-400 pt-2">CONTRATADA — {data.contractor.legalName} / ALGENRI</div><p className="mt-2 text-xs text-slate-500">Representante: {data.contractor.representative}</p></div></div>
  </article>
  <style jsx global>{`@media print{body{background:white!important}.contract-paper{padding:18mm 14mm!important}.print\\:hidden{display:none!important}@page{size:A4;margin:0}}`}</style>
 </div></main>
}
