import { FieldValue } from "firebase-admin/firestore";
import { z } from "zod";
import { internalAuthResponse, requireAlgenriInternalUser } from "@/lib/briefing/internal-auth";
import { getAdminDb } from "@/lib/firebase/admin";
import { getStudioProject } from "@/lib/studio/project-store";

const itemSchema=z.object({id:z.string().trim().min(1).max(80),name:z.string().trim().min(1).max(160),role:z.string().trim().max(120).optional().default(""),description:z.string().trim().max(1200).optional().default(""),wardrobe:z.string().trim().max(900).optional().default(""),behavior:z.string().trim().max(700).optional().default(""),locked:z.boolean().default(true)});
const environmentSchema=z.object({id:z.string().trim().min(1).max(80),name:z.string().trim().min(1).max(160),description:z.string().trim().max(1400).optional().default(""),lighting:z.string().trim().max(700).optional().default(""),camera:z.string().trim().max(700).optional().default(""),locked:z.boolean().default(true)});
const schema=z.object({characters:z.array(itemSchema).max(12),environments:z.array(environmentSchema).max(10),globalVisualRules:z.string().trim().max(2200).default(""),continuityNotes:z.string().trim().max(1800).default("")});

async function authorize(request:Request,projectId:string){const user=await requireAlgenriInternalUser(request);const project=await getStudioProject(projectId);if(!project)return{response:Response.json({ok:false,error:"not_found"},{status:404})};if(project.ownerUid&&project.ownerUid!==user.uid)return{response:Response.json({ok:false,error:"forbidden"},{status:403})};return{project};}
function normalize(value:any){return{characters:Array.isArray(value?.characters)?value.characters:[],environments:Array.isArray(value?.environments)?value.environments:[],globalVisualRules:String(value?.globalVisualRules??""),continuityNotes:String(value?.continuityNotes??""),updatedAt:value?.updatedAt??null};}
function aggregateCharacters(items:any[]){return items.filter(x=>x?.locked!==false).map((x,i)=>`${i+1}. ${x.name}${x.role?` (${x.role})`:""}: ${x.description||""}${x.wardrobe?` Figurino: ${x.wardrobe}.`:""}${x.behavior?` Comportamento: ${x.behavior}.`:""}`).join("\n");}
function aggregateEnvironments(items:any[]){return items.filter(x=>x?.locked!==false).map((x,i)=>`${i+1}. ${x.name}: ${x.description||""}${x.lighting?` Luz: ${x.lighting}.`:""}${x.camera?` Câmera: ${x.camera}.`:""}`).join("\n");}

export async function GET(request:Request,context:{params:Promise<{projectId:string}>}){try{const{projectId}=await context.params;const auth=await authorize(request,projectId);if(auth.response)return auth.response;return Response.json({ok:true,visualBible:normalize(auth.project.visualBible)});}catch(error){const auth=internalAuthResponse(error);if(auth)return auth;return Response.json({ok:false,error:"studio_visual_bible_load_failed"},{status:500});}}

export async function PATCH(request:Request,context:{params:Promise<{projectId:string}>}){try{const{projectId}=await context.params;const auth=await authorize(request,projectId);if(auth.response)return auth.response;const parsed=schema.safeParse(await request.json());if(!parsed.success)return Response.json({ok:false,error:"invalid_request",issues:parsed.error.issues},{status:400});const updatedAt=new Date().toISOString();const visualBible={...parsed.data,updatedAt};const project=auth.project as any;const currentContinuity=project.continuity??{};const characters=aggregateCharacters(parsed.data.characters)||String(currentContinuity.characters??"");const environment=aggregateEnvironments(parsed.data.environments)||String(currentContinuity.environment??"");const visualRules=[parsed.data.globalVisualRules,parsed.data.continuityNotes].filter(Boolean).join("\n");const db=await getAdminDb();await db.collection("studioProjects").doc(projectId).set({visualBible,continuity:{...currentContinuity,characters,environment,visualRules:visualRules||currentContinuity.visualRules||"",updatedAt},routing:{state:"not_started",generatedAt:null,routes:[],totalEstimatedCredits:null,fullyExecutable:false,providerCoverage:null},updatedAt:FieldValue.serverTimestamp()},{merge:true});return Response.json({ok:true,visualBible,continuity:{...currentContinuity,characters,environment,visualRules:visualRules||currentContinuity.visualRules||"",updatedAt}});}catch(error){const auth=internalAuthResponse(error);if(auth)return auth;console.error("studio_visual_bible_save_failed",error);return Response.json({ok:false,error:"studio_visual_bible_save_failed"},{status:500});}}
